CREATE EXTENSION IF NOT EXISTS pgcrypto;

SET TIME ZONE 'Asia/Kolkata';

CREATE OR REPLACE FUNCTION public.app_now()
RETURNS timestamptz
LANGUAGE sql
STABLE
AS $$ SELECT CURRENT_TIMESTAMP; $$;

CREATE TABLE IF NOT EXISTS "Tenants" (
    "TenantId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Name" varchar(160) NOT NULL,
    "Slug" varchar(120) NOT NULL,
    "OwnerEmail" varchar(256) NOT NULL,
    "PlanCode" varchar(40) NOT NULL DEFAULT 'trial',
    "TrialStartAtUtc" timestamptz NULL,
    "TrialEndAtUtc" timestamptz NULL,
    "SubscriptionStatusCode" varchar(32) NOT NULL DEFAULT 'Trialing',
    "AccountStatusCode" varchar(32) NOT NULL DEFAULT 'Active',
    "SubscriptionUpdatedAtUtc" timestamptz NULL,
    "SubscriptionNotes" varchar(500) NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_Tenants_Slug" UNIQUE ("Slug"),
    CONSTRAINT "UQ_Tenants_OwnerEmail" UNIQUE ("OwnerEmail"),
    CONSTRAINT "CK_Tenants_SubscriptionStatusCode" CHECK ("SubscriptionStatusCode" IN ('Trialing', 'Active', 'ManualActive', 'PastDue', 'Suspended', 'Cancelled', 'Expired')),
    CONSTRAINT "CK_Tenants_AccountStatusCode" CHECK ("AccountStatusCode" IN ('Active', 'Inactive'))
);

CREATE TABLE IF NOT EXISTS "Users" (
    "UserId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email" varchar(256) NOT NULL,
    "DisplayName" varchar(160) NOT NULL,
    "PasswordHash" varchar(512) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_Users_Email" UNIQUE ("Email")
);

CREATE TABLE IF NOT EXISTS "SuperAdminUsers" (
    "SuperAdminUserId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email" varchar(256) NOT NULL,
    "DisplayName" varchar(160) NOT NULL,
    "PasswordHash" varchar(512) NOT NULL,
    "RoleCode" varchar(40) NOT NULL DEFAULT 'super_admin',
    "IsActive" boolean NOT NULL DEFAULT true,
    "LastLoginAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_SuperAdminUsers_Email" UNIQUE ("Email"),
    CONSTRAINT "CK_SuperAdminUsers_RoleCode" CHECK ("RoleCode" IN ('super_admin', 'support_admin', 'sales_admin'))
);

CREATE TABLE IF NOT EXISTS "Branches" (
    "BranchId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "Name" varchar(160) NOT NULL,
    "PhoneNumber" varchar(32) NULL,
    "AddressLine1" varchar(220) NULL,
    "AddressLine2" varchar(220) NULL,
    "City" varchar(120) NULL,
    "State" varchar(120) NULL,
    "PostalCode" varchar(32) NULL,
    "CountryCode" char(2) NOT NULL DEFAULT 'IN',
    "LogoUrl" varchar(1000) NULL,
    "LogoPublicId" varchar(300) NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_Branches_TenantId_Name" UNIQUE ("TenantId", "Name")
);

CREATE TABLE IF NOT EXISTS "TenantUsers" (
    "TenantUserId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "UserId" uuid NOT NULL REFERENCES "Users" ("UserId"),
    "BranchId" uuid NULL REFERENCES "Branches" ("BranchId"),
    "RoleCode" varchar(40) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "CK_TenantUsers_RoleCode" CHECK ("RoleCode" IN ('owner', 'admin', 'manager', 'kitchen', 'waiter', 'staff')),
    CONSTRAINT "UQ_TenantUsers_TenantId_UserId" UNIQUE ("TenantId", "UserId")
);

CREATE TABLE IF NOT EXISTS "BranchOrderSettings" (
    "BranchOrderSettingsId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "EnableDirectQrOrdering" boolean NOT NULL DEFAULT false,
    "RequireCustomerName" boolean NOT NULL DEFAULT false,
    "RequireCustomerWhatsApp" boolean NOT NULL DEFAULT false,
    "WaiterCallEnabled" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_BranchOrderSettings_TenantId_BranchId" UNIQUE ("TenantId", "BranchId")
);

CREATE TABLE IF NOT EXISTS "MenuCategories" (
    "MenuCategoryId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "Name" varchar(120) NOT NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0 CHECK ("DisplayOrder" >= 0),
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_MenuCategories_TenantId_BranchId_Name" UNIQUE ("TenantId", "BranchId", "Name")
);

CREATE TABLE IF NOT EXISTS "MenuItems" (
    "MenuItemId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "MenuCategoryId" uuid NOT NULL REFERENCES "MenuCategories" ("MenuCategoryId"),
    "Name" varchar(160) NOT NULL,
    "Description" varchar(1000) NULL,
    "Price" numeric(10,2) NOT NULL CHECK ("Price" >= 0),
    "DietTypeCode" varchar(32) NOT NULL DEFAULT 'Unspecified',
    "IsAvailable" boolean NOT NULL DEFAULT true,
    "IsActive" boolean NOT NULL DEFAULT true,
    "DisplayOrder" integer NOT NULL DEFAULT 0 CHECK ("DisplayOrder" >= 0),
    "ImageUrl" varchar(1000) NULL,
    "ImageAltText" varchar(200) NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_MenuItems_TenantId_BranchId_MenuCategoryId_Name" UNIQUE ("TenantId", "BranchId", "MenuCategoryId", "Name"),
    CONSTRAINT "CK_MenuItems_DietTypeCode" CHECK ("DietTypeCode" IN ('Unspecified', 'Veg', 'NonVeg', 'Vegan', 'Egg', 'Jain'))
);

CREATE TABLE IF NOT EXISTS "MenuItemVariants" (
    "MenuItemVariantId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "MenuItemId" uuid NOT NULL REFERENCES "MenuItems" ("MenuItemId"),
    "Name" varchar(80) NOT NULL,
    "Price" numeric(10,2) NOT NULL CHECK ("Price" >= 0),
    "IsAvailable" boolean NOT NULL DEFAULT true,
    "DisplayOrder" integer NOT NULL DEFAULT 0 CHECK ("DisplayOrder" >= 0),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_MenuItemVariants_MenuItemId_Name" UNIQUE ("MenuItemId", "Name")
);

CREATE TABLE IF NOT EXISTS "BranchOffers" (
    "BranchOfferId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "Title" varchar(160) NOT NULL,
    "Subtitle" varchar(300) NULL,
    "DiscountText" varchar(80) NULL,
    "ImageUrl" varchar(1000) NULL,
    "ImageAltText" varchar(200) NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0 CHECK ("DisplayOrder" >= 0),
    "StartsAtUtc" timestamptz NULL,
    "EndsAtUtc" timestamptz NULL,
    "DiscountTypeCode" varchar(32) NOT NULL DEFAULT 'DisplayOnly',
    "DiscountValue" numeric(10,2) NOT NULL DEFAULT 0,
    "MinimumOrderAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "MaxDiscountAmount" numeric(10,2) NULL,
    "AutoApply" boolean NOT NULL DEFAULT false,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "CK_BranchOffers_DiscountTypeCode" CHECK ("DiscountTypeCode" IN ('DisplayOnly', 'Percentage', 'FixedAmount'))
);

CREATE TABLE IF NOT EXISTS "BranchTables" (
    "TableId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "Name" varchar(80) NOT NULL,
    "DisplayOrder" integer NOT NULL DEFAULT 0 CHECK ("DisplayOrder" >= 0),
    "QrToken" varchar(80) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_BranchTables_TenantId_BranchId_Name" UNIQUE ("TenantId", "BranchId", "Name"),
    CONSTRAINT "UQ_BranchTables_QrToken" UNIQUE ("QrToken")
);

CREATE TABLE IF NOT EXISTS "Customers" (
    "CustomerId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "Name" varchar(120) NOT NULL,
    "WhatsAppNumber" varchar(32) NULL,
    "VisitCount" integer NOT NULL DEFAULT 0,
    "LastVisitAtUtc" timestamptz NULL,
    "MarketingConsent" boolean NOT NULL DEFAULT false,
    "MarketingConsentSource" varchar(80) NULL,
    "MarketingConsentAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_Customers_TenantId_BranchId_WhatsAppNumber" UNIQUE ("TenantId", "BranchId", "WhatsAppNumber")
);

CREATE TABLE IF NOT EXISTS "Orders" (
    "OrderId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "TableId" uuid NOT NULL REFERENCES "BranchTables" ("TableId"),
    "CustomerId" uuid NULL REFERENCES "Customers" ("CustomerId"),
    "OrderStatusCode" varchar(32) NOT NULL DEFAULT 'Placed',
    "CustomerName" varchar(120) NULL,
    "CustomerWhatsApp" varchar(32) NULL,
    "Notes" varchar(500) NULL,
    "SubtotalAmount" numeric(10,2) NOT NULL CHECK ("SubtotalAmount" >= 0),
    "AppliedBranchOfferId" uuid NULL REFERENCES "BranchOffers" ("BranchOfferId"),
    "AppliedOfferTitle" varchar(160) NULL,
    "AppliedOfferDiscountAmount" numeric(10,2) NOT NULL DEFAULT 0 CHECK ("AppliedOfferDiscountAmount" >= 0),
    "TotalAmount" numeric(10,2) NOT NULL CHECK ("TotalAmount" >= 0),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8)
);

CREATE TABLE IF NOT EXISTS "OrderItems" (
    "OrderItemId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId"),
    "MenuItemId" uuid NOT NULL REFERENCES "MenuItems" ("MenuItemId"),
    "MenuItemVariantId" uuid NULL REFERENCES "MenuItemVariants" ("MenuItemVariantId"),
    "MenuItemName" varchar(160) NOT NULL,
    "VariantName" varchar(80) NULL,
    "ItemNote" varchar(200) NULL,
    "DietTypeCode" varchar(32) NOT NULL DEFAULT 'Unspecified',
    "UnitPrice" numeric(10,2) NOT NULL CHECK ("UnitPrice" >= 0),
    "Quantity" integer NOT NULL CHECK ("Quantity" > 0),
    "LineTotal" numeric(10,2) NOT NULL CHECK ("LineTotal" >= 0),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "CK_OrderItems_DietTypeCode" CHECK ("DietTypeCode" IN ('Unspecified', 'Veg', 'NonVeg', 'Vegan', 'Egg', 'Jain'))
);

CREATE TABLE IF NOT EXISTS "OrderStatusHistory" (
    "OrderStatusHistoryId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId"),
    "StatusCode" varchar(32) NOT NULL,
    "Reason" varchar(300) NULL,
    "ChangedByUserId" uuid NULL REFERENCES "Users" ("UserId"),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now())
);

CREATE TABLE IF NOT EXISTS "WaiterCalls" (
    "WaiterCallId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "TableId" uuid NOT NULL REFERENCES "BranchTables" ("TableId"),
    "StatusCode" varchar(32) NOT NULL DEFAULT 'Open',
    "CustomerName" varchar(120) NULL,
    "Note" varchar(500) NULL,
    "ResolvedByUserId" uuid NULL REFERENCES "Users" ("UserId"),
    "ResolvedAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8)
);

CREATE TABLE IF NOT EXISTS "WhatsAppCampaigns" (
    "CampaignId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NULL REFERENCES "Branches" ("BranchId"),
    "Name" varchar(120) NOT NULL,
    "TargetSegment" varchar(40) NOT NULL,
    "MessageText" varchar(1000) NOT NULL,
    "RecipientCount" integer NOT NULL DEFAULT 0,
    "StatusCode" varchar(32) NOT NULL DEFAULT 'Draft',
    "QueuedAtUtc" timestamptz NULL,
    "StartedAtUtc" timestamptz NULL,
    "CompletedAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8)
);

CREATE TABLE IF NOT EXISTS "WhatsAppCampaignRecipients" (
    "CampaignRecipientId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "CampaignId" uuid NOT NULL REFERENCES "WhatsAppCampaigns" ("CampaignId"),
    "CustomerId" uuid NOT NULL REFERENCES "Customers" ("CustomerId"),
    "WhatsAppNumber" varchar(32) NOT NULL,
    "StatusCode" varchar(32) NOT NULL DEFAULT 'Pending',
    "SentAtUtc" timestamptz NULL,
    "FailedAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now())
);

CREATE TABLE IF NOT EXISTS "AdminNotifications" (
    "AdminNotificationId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NULL REFERENCES "Branches" ("BranchId"),
    "TypeCode" varchar(40) NOT NULL,
    "Title" varchar(160) NOT NULL,
    "Message" varchar(500) NOT NULL,
    "TargetUrl" varchar(500) NOT NULL DEFAULT '/admin',
    "EntityType" varchar(80) NULL,
    "EntityId" uuid NULL,
    "IsRead" boolean NOT NULL DEFAULT false,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "ReadAtUtc" timestamptz NULL
);

CREATE TABLE IF NOT EXISTS "BranchBillingSettings" (
    "BranchBillingSettingsId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "TaxEnabled" boolean NOT NULL DEFAULT false,
    "TaxName" varchar(40) NULL,
    "TaxRate" numeric(6,3) NOT NULL DEFAULT 0,
    "TaxMode" varchar(20) NOT NULL DEFAULT 'Exclusive',
    "ServiceChargeEnabled" boolean NOT NULL DEFAULT false,
    "ServiceChargeName" varchar(60) NULL,
    "ServiceChargeRate" numeric(6,3) NOT NULL DEFAULT 0,
    "DiscountEnabled" boolean NOT NULL DEFAULT false,
    "StaffCanApplyDiscount" boolean NOT NULL DEFAULT false,
    "RoundingMode" varchar(20) NOT NULL DEFAULT 'None',
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_BranchBillingSettings_TenantId_BranchId" UNIQUE ("TenantId", "BranchId")
);

CREATE TABLE IF NOT EXISTS "OrderBills" (
    "OrderBillId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId"),
    "SubtotalAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "DiscountAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "AppliedBranchOfferId" uuid NULL REFERENCES "BranchOffers" ("BranchOfferId"),
    "AppliedOfferTitle" varchar(160) NULL,
    "TaxAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "ServiceChargeAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "TaxableAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "RoundingAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "TotalAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "BillNumber" varchar(40) NOT NULL DEFAULT '',
    "PaymentStatusCode" varchar(32) NOT NULL DEFAULT 'Unpaid',
    "PaymentMethod" varchar(80) NULL,
    "PaidAtUtc" timestamptz NULL,
    "RefundStatusCode" varchar(32) NOT NULL DEFAULT 'NotRefunded',
    "RefundAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "RefundReason" varchar(300) NULL,
    "RefundedAtUtc" timestamptz NULL,
    "TaxEnabled" boolean NOT NULL DEFAULT false,
    "TaxName" varchar(40) NOT NULL DEFAULT '',
    "TaxRate" numeric(6,3) NOT NULL DEFAULT 0,
    "TaxMode" varchar(20) NOT NULL DEFAULT 'Exclusive',
    "ServiceChargeEnabled" boolean NOT NULL DEFAULT false,
    "ServiceChargeName" varchar(60) NOT NULL DEFAULT '',
    "ServiceChargeRate" numeric(6,3) NOT NULL DEFAULT 0,
    "DiscountEnabled" boolean NOT NULL DEFAULT false,
    "GeneratedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_OrderBills_OrderId" UNIQUE ("OrderId")
);

CREATE TABLE IF NOT EXISTS "OrderBillAuditEntries" (
    "OrderBillAuditEntryId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId"),
    "OrderBillId" uuid NOT NULL REFERENCES "OrderBills" ("OrderBillId"),
    "ActionCode" varchar(40) NOT NULL,
    "Reason" varchar(300) NULL,
    "ChangedByUserId" uuid NULL REFERENCES "Users" ("UserId"),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now())
);

CREATE TABLE IF NOT EXISTS "OrderFeedback" (
    "OrderFeedbackId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId"),
    "Rating" integer NOT NULL CHECK ("Rating" BETWEEN 1 AND 5),
    "Comment" varchar(1000) NULL,
    "CustomerName" varchar(120) NULL,
    "CustomerWhatsApp" varchar(32) NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    CONSTRAINT "UQ_OrderFeedback_OrderId" UNIQUE ("OrderId")
);

CREATE TABLE IF NOT EXISTS "SuperAdminAuditEntries" (
    "SuperAdminAuditEntryId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NULL REFERENCES "Tenants" ("TenantId"),
    "SuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "ActionCode" varchar(80) NOT NULL,
    "Summary" varchar(500) NOT NULL,
    "MetadataJson" text NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now())
);

CREATE TABLE IF NOT EXISTS "SuperAdminInternalNotes" (
    "SuperAdminInternalNoteId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId") ON DELETE CASCADE,
    "Note" varchar(1000) NOT NULL,
    "CreatedBySuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now())
);
