CREATE TABLE IF NOT EXISTS "SuperAdminUsers" (
    "SuperAdminUserId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email" varchar(256) NOT NULL,
    "DisplayName" varchar(160) NOT NULL,
    "PasswordHash" varchar(512) NOT NULL,
    "RoleCode" varchar(40) NOT NULL DEFAULT 'super_admin',
    "IsActive" boolean NOT NULL DEFAULT true,
    "LastLoginAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now()),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_SuperAdminUsers_Email" UNIQUE ("Email"),
    CONSTRAINT "CK_SuperAdminUsers_RoleCode" CHECK ("RoleCode" IN ('super_admin', 'support_admin', 'sales_admin'))
);

CREATE TABLE IF NOT EXISTS "SuperAdminAuditEntries" (
    "SuperAdminAuditEntryId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NULL REFERENCES "Tenants" ("TenantId"),
    "SuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "ActionCode" varchar(80) NOT NULL,
    "Summary" varchar(500) NOT NULL,
    "MetadataJson" text NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now())
);

CREATE TABLE IF NOT EXISTS "SuperAdminInternalNotes" (
    "SuperAdminInternalNoteId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId") ON DELETE CASCADE,
    "Note" varchar(1000) NOT NULL,
    "CreatedBySuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT (public.app_now())
);

CREATE INDEX IF NOT EXISTS "IX_SuperAdminAuditEntries_TenantId_CreatedAtUtc" ON "SuperAdminAuditEntries" ("TenantId", "CreatedAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_SuperAdminAuditEntries_CreatedAtUtc" ON "SuperAdminAuditEntries" ("CreatedAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_SuperAdminInternalNotes_TenantId_CreatedAtUtc" ON "SuperAdminInternalNotes" ("TenantId", "CreatedAtUtc" DESC);
