-- Adds promo-code offers, usage limits, and offer redemption tracking.

ALTER TABLE "BranchOffers"
ADD COLUMN IF NOT EXISTS "PromoCode" varchar(40) NULL,
ADD COLUMN IF NOT EXISTS "RequiresPromoCode" boolean NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "MaxTotalRedemptions" integer NULL,
ADD COLUMN IF NOT EXISTS "MaxRedemptionsPerCustomer" integer NULL,
ADD COLUMN IF NOT EXISTS "MaxRedemptionsPerDay" integer NULL;

CREATE UNIQUE INDEX IF NOT EXISTS "UX_BranchOffers_BranchId_PromoCode"
ON "BranchOffers" ("BranchId", lower("PromoCode"))
WHERE "PromoCode" IS NOT NULL;

CREATE TABLE IF NOT EXISTS "BranchOfferRedemptions" (
    "BranchOfferRedemptionId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId") ON DELETE CASCADE,
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId") ON DELETE CASCADE,
    "BranchOfferId" uuid NOT NULL REFERENCES "BranchOffers" ("BranchOfferId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId") ON DELETE CASCADE,
    "CustomerId" uuid NULL REFERENCES "Customers" ("CustomerId") ON DELETE SET NULL,
    "CustomerWhatsApp" varchar(32) NULL,
    "PromoCode" varchar(40) NULL,
    "RedemptionTypeCode" varchar(32) NOT NULL,
    "SubtotalAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "DiscountAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "FinalTotalAmount" numeric(10,2) NOT NULL DEFAULT 0,
    "RedeemedAtUtc" timestamptz NOT NULL DEFAULT public.app_now(),
    CONSTRAINT "UQ_BranchOfferRedemptions_OrderId" UNIQUE ("OrderId"),
    CONSTRAINT "CK_BranchOfferRedemptions_RedemptionTypeCode" CHECK ("RedemptionTypeCode" IN ('AutoApplied','PromoCode'))
);

CREATE INDEX IF NOT EXISTS "IX_BranchOfferRedemptions_Offer_RedeemedAtUtc"
ON "BranchOfferRedemptions" ("BranchOfferId", "RedeemedAtUtc" DESC);

CREATE INDEX IF NOT EXISTS "IX_BranchOfferRedemptions_Branch_RedeemedAtUtc"
ON "BranchOfferRedemptions" ("TenantId", "BranchId", "RedeemedAtUtc" DESC);

CREATE OR REPLACE FUNCTION public.branchoffer_create(
    p_tenantid uuid,
    p_branchid uuid,
    p_branchofferid uuid,
    p_title text,
    p_subtitle text,
    p_discounttext text,
    p_imageurl text,
    p_imagealttext text,
    p_displayorder integer,
    p_startsatutc timestamptz,
    p_endsatutc timestamptz,
    p_discounttypecode text,
    p_discountvalue numeric,
    p_minimumorderamount numeric,
    p_maxdiscountamount numeric,
    p_autoapply boolean,
    p_promocode text,
    p_requirespromocode boolean,
    p_maxtotalredemptions integer,
    p_maxredemptionspercustomer integer,
    p_maxredemptionsperday integer)
RETURNS SETOF "BranchOffers"
LANGUAGE plpgsql AS $$
BEGIN
    INSERT INTO "BranchOffers" (
        "BranchOfferId","TenantId","BranchId","Title","Subtitle","DiscountText","ImageUrl","ImageAltText","DisplayOrder",
        "StartsAtUtc","EndsAtUtc","DiscountTypeCode","DiscountValue","MinimumOrderAmount","MaxDiscountAmount","AutoApply",
        "PromoCode","RequiresPromoCode","MaxTotalRedemptions","MaxRedemptionsPerCustomer","MaxRedemptionsPerDay")
    VALUES (
        p_branchofferid,p_tenantid,p_branchid,p_title,p_subtitle,p_discounttext,p_imageurl,p_imagealttext,p_displayorder,
        p_startsatutc,p_endsatutc,p_discounttypecode,p_discountvalue,p_minimumorderamount,p_maxdiscountamount,p_autoapply,
        NULLIF(upper(btrim(p_promocode)),''),p_requirespromocode,p_maxtotalredemptions,p_maxredemptionspercustomer,p_maxredemptionsperday);

    RETURN QUERY SELECT bo.* FROM "BranchOffers" bo WHERE bo."BranchOfferId"=p_branchofferid;
END;
$$;

CREATE OR REPLACE FUNCTION public.branchoffer_update(
    p_tenantid uuid,
    p_branchid uuid,
    p_branchofferid uuid,
    p_title text,
    p_subtitle text,
    p_discounttext text,
    p_imageurl text,
    p_imagealttext text,
    p_displayorder integer,
    p_startsatutc timestamptz,
    p_endsatutc timestamptz,
    p_discounttypecode text,
    p_discountvalue numeric,
    p_minimumorderamount numeric,
    p_maxdiscountamount numeric,
    p_autoapply boolean,
    p_promocode text,
    p_requirespromocode boolean,
    p_maxtotalredemptions integer,
    p_maxredemptionspercustomer integer,
    p_maxredemptionsperday integer,
    p_isactive boolean)
RETURNS SETOF "BranchOffers"
LANGUAGE plpgsql AS $$
BEGIN
    UPDATE "BranchOffers" bo
    SET "Title"=p_title,
        "Subtitle"=p_subtitle,
        "DiscountText"=p_discounttext,
        "ImageUrl"=p_imageurl,
        "ImageAltText"=p_imagealttext,
        "DisplayOrder"=p_displayorder,
        "StartsAtUtc"=p_startsatutc,
        "EndsAtUtc"=p_endsatutc,
        "DiscountTypeCode"=p_discounttypecode,
        "DiscountValue"=p_discountvalue,
        "MinimumOrderAmount"=p_minimumorderamount,
        "MaxDiscountAmount"=p_maxdiscountamount,
        "AutoApply"=p_autoapply,
        "IsActive"=p_isactive,
        "PromoCode"=NULLIF(upper(btrim(p_promocode)),''),
        "RequiresPromoCode"=p_requirespromocode,
        "MaxTotalRedemptions"=p_maxtotalredemptions,
        "MaxRedemptionsPerCustomer"=p_maxredemptionspercustomer,
        "MaxRedemptionsPerDay"=p_maxredemptionsperday,
        "UpdatedAtUtc"=public.app_now()
    WHERE bo."TenantId"=p_tenantid AND bo."BranchId"=p_branchid AND bo."BranchOfferId"=p_branchofferid;

    RETURN QUERY SELECT bo.* FROM "BranchOffers" bo WHERE bo."BranchOfferId"=p_branchofferid;
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(
    p_qrtoken text,
    p_orderid uuid,
    p_customername text,
    p_customerwhatsapp text,
    p_notes text,
    p_itemsjson text,
    p_marketingconsent boolean,
    p_marketingconsentsource text,
    p_promocode text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
DECLARE
    ctx record;
    customer_id uuid;
    subtotal numeric;
    billing record;
    selected record;
    offer_found boolean := false;
    offer_id uuid;
    offer_title varchar;
    discount numeric := 0;
    clean_promo text := NULLIF(upper(btrim(p_promocode)),'');
    redemption_type text := 'AutoApplied';
    taxable numeric := 0;
    tax numeric := 0;
    service_charge numeric := 0;
    total_before_rounding numeric := 0;
    rounding_amount numeric := 0;
    payable_total numeric := 0;
BEGIN
    PERFORM public.publicqr_assert_tenant_available(p_qrtoken);

    SELECT bt."TenantId",bt."BranchId",bt."TableId",COALESCE(bos."EnableDirectQrOrdering",false) enabled,COALESCE(bos."RequireCustomerName",false) req_name,COALESCE(bos."RequireCustomerWhatsApp",false) req_whatsapp
    INTO ctx FROM "BranchTables" bt JOIN "Branches" b ON b."BranchId"=bt."BranchId" AND b."IsActive" LEFT JOIN "BranchOrderSettings" bos ON bos."BranchId"=bt."BranchId" WHERE bt."QrToken"=p_qrtoken AND bt."IsActive";
    IF ctx."TableId" IS NULL THEN PERFORM public.raise_app_error(51701); END IF;
    IF NOT ctx.enabled THEN PERFORM public.raise_app_error(51702); END IF;
    IF ctx.req_name AND NULLIF(btrim(p_customername),'') IS NULL THEN PERFORM public.raise_app_error(51703); END IF;
    IF ctx.req_whatsapp AND NULLIF(btrim(p_customerwhatsapp),'') IS NULL THEN PERFORM public.raise_app_error(51704); END IF;

    CREATE TEMP TABLE tmp_order_items ON COMMIT DROP AS
    SELECT gen_random_uuid() "OrderItemId", mi."MenuItemId", v."MenuItemVariantId", mi."Name" "MenuItemName", v."Name" "VariantName", NULLIF(x->>'itemNote','') "ItemNote", mi."DietTypeCode", COALESCE(v."Price",mi."Price") "UnitPrice", GREATEST(COALESCE((x->>'quantity')::integer,0),0) "Quantity"
    FROM jsonb_array_elements(COALESCE(NULLIF(p_itemsjson,'')::jsonb,'[]'::jsonb)) x
    JOIN "MenuItems" mi ON mi."MenuItemId"=(x->>'menuItemId')::uuid AND mi."TenantId"=ctx."TenantId" AND mi."BranchId"=ctx."BranchId" AND mi."IsActive" AND mi."IsAvailable"
    LEFT JOIN "MenuItemVariants" v ON v."MenuItemVariantId"=NULLIF(x->>'menuItemVariantId','')::uuid AND v."MenuItemId"=mi."MenuItemId" AND v."IsAvailable";
    DELETE FROM tmp_order_items WHERE "Quantity" <= 0;
    IF NOT EXISTS (SELECT 1 FROM tmp_order_items) THEN PERFORM public.raise_app_error(51705); END IF;
    SELECT SUM("UnitPrice"*"Quantity") INTO subtotal FROM tmp_order_items;

    IF NULLIF(btrim(p_customerwhatsapp),'') IS NOT NULL THEN
        INSERT INTO "Customers" ("CustomerId","TenantId","BranchId","Name","WhatsAppNumber","VisitCount","LastVisitAtUtc","MarketingConsent","MarketingConsentSource","MarketingConsentAtUtc")
        VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",COALESCE(NULLIF(p_customername,''),'Guest'),p_customerwhatsapp,1,public.app_now(),p_marketingconsent,p_marketingconsentsource,CASE WHEN p_marketingconsent THEN public.app_now() END)
        ON CONFLICT ON CONSTRAINT "UQ_Customers_TenantId_BranchId_WhatsAppNumber" DO UPDATE SET "Name"=COALESCE(NULLIF(EXCLUDED."Name",''),"Customers"."Name"),"VisitCount"="Customers"."VisitCount"+1,"LastVisitAtUtc"=public.app_now(),"MarketingConsent"=("Customers"."MarketingConsent" OR EXCLUDED."MarketingConsent"),"UpdatedAtUtc"=public.app_now()
        RETURNING "CustomerId" INTO customer_id;
    END IF;

    SELECT
        COALESCE(bs."TaxEnabled",false) "TaxEnabled",
        COALESCE(bs."TaxRate",0) "TaxRate",
        COALESCE(bs."TaxMode",'Exclusive') "TaxMode",
        COALESCE(bs."ServiceChargeEnabled",false) "ServiceChargeEnabled",
        COALESCE(bs."ServiceChargeRate",0) "ServiceChargeRate",
        COALESCE(bs."RoundingMode",'None') "RoundingMode"
    INTO billing
    FROM "Branches" b
    LEFT JOIN "BranchBillingSettings" bs ON bs."TenantId"=b."TenantId" AND bs."BranchId"=b."BranchId"
    WHERE b."TenantId"=ctx."TenantId" AND b."BranchId"=ctx."BranchId";

    SELECT selected_offer.*
    INTO selected
    FROM (
        SELECT bo.*,
               round(LEAST(
                   subtotal,
                   GREATEST(
                       0,
                       CASE
                           WHEN bo."MaxDiscountAmount" IS NOT NULL THEN LEAST(
                               CASE bo."DiscountTypeCode"
                                   WHEN 'Percentage' THEN round(subtotal * bo."DiscountValue" / 100,2)
                                   ELSE round(bo."DiscountValue",2)
                               END,
                               bo."MaxDiscountAmount"
                           )
                           ELSE CASE bo."DiscountTypeCode"
                               WHEN 'Percentage' THEN round(subtotal * bo."DiscountValue" / 100,2)
                               ELSE round(bo."DiscountValue",2)
                           END
                       END
                   )
               ),2) AS computed_discount
        FROM "BranchOffers" bo
        WHERE bo."TenantId"=ctx."TenantId"
          AND bo."BranchId"=ctx."BranchId"
          AND bo."IsActive"
          AND bo."DiscountTypeCode" <> 'DisplayOnly'
          AND bo."DiscountValue" > 0
          AND subtotal >= bo."MinimumOrderAmount"
          AND (bo."StartsAtUtc" IS NULL OR bo."StartsAtUtc" <= public.app_now())
          AND (bo."EndsAtUtc" IS NULL OR bo."EndsAtUtc" >= public.app_now())
          AND (
              (clean_promo IS NOT NULL AND upper(bo."PromoCode") = clean_promo)
              OR (clean_promo IS NULL AND bo."AutoApply" AND NOT bo."RequiresPromoCode")
          )
        ORDER BY CASE WHEN clean_promo IS NOT NULL AND upper(bo."PromoCode") = clean_promo THEN 0 ELSE 1 END,
                 computed_discount DESC, bo."DisplayOrder", bo."Title"
        LIMIT 1
    ) selected_offer;
    offer_found := FOUND;

    IF clean_promo IS NOT NULL AND NOT offer_found THEN
        PERFORM public.raise_app_error(52101);
    END IF;

    IF offer_found THEN
        redemption_type := CASE WHEN clean_promo IS NOT NULL THEN 'PromoCode' ELSE 'AutoApplied' END;

        IF selected."MaxTotalRedemptions" IS NOT NULL AND
           (SELECT COUNT(*) FROM "BranchOfferRedemptions" r WHERE r."BranchOfferId"=selected."BranchOfferId") >= selected."MaxTotalRedemptions" THEN
            PERFORM public.raise_app_error(52102);
        END IF;

        IF selected."MaxRedemptionsPerDay" IS NOT NULL AND
           (SELECT COUNT(*) FROM "BranchOfferRedemptions" r WHERE r."BranchOfferId"=selected."BranchOfferId" AND r."RedeemedAtUtc" >= date_trunc('day', public.app_now())) >= selected."MaxRedemptionsPerDay" THEN
            PERFORM public.raise_app_error(52102);
        END IF;

        IF selected."MaxRedemptionsPerCustomer" IS NOT NULL AND NULLIF(btrim(p_customerwhatsapp),'') IS NOT NULL AND
           (SELECT COUNT(*) FROM "BranchOfferRedemptions" r WHERE r."BranchOfferId"=selected."BranchOfferId" AND r."CustomerWhatsApp"=p_customerwhatsapp) >= selected."MaxRedemptionsPerCustomer" THEN
            PERFORM public.raise_app_error(52103);
        END IF;

        offer_id := selected."BranchOfferId";
        offer_title := selected."Title";
        discount := COALESCE(selected.computed_discount,0);
    END IF;

    taxable := round(GREATEST(subtotal - discount,0),2);
    IF billing."TaxEnabled" AND billing."TaxRate" > 0 THEN
        tax := CASE
            WHEN billing."TaxMode" = 'Inclusive' THEN round(taxable - taxable / (1 + billing."TaxRate" / 100),2)
            ELSE round(taxable * billing."TaxRate" / 100,2)
        END;
    END IF;
    IF billing."ServiceChargeEnabled" AND billing."ServiceChargeRate" > 0 THEN
        service_charge := round(taxable * billing."ServiceChargeRate" / 100,2);
    END IF;
    total_before_rounding := round((CASE WHEN billing."TaxMode" = 'Inclusive' THEN taxable ELSE taxable + tax END) + service_charge,2);
    rounding_amount := CASE WHEN billing."RoundingMode" IN ('NearestRupee','Nearest') THEN round(total_before_rounding) - total_before_rounding ELSE 0 END;
    payable_total := round(total_before_rounding + rounding_amount,2);

    INSERT INTO "Orders" ("OrderId","TenantId","BranchId","TableId","CustomerId","CustomerName","CustomerWhatsApp","Notes","SubtotalAmount","AppliedBranchOfferId","AppliedOfferTitle","AppliedOfferDiscountAmount","TotalAmount")
    VALUES (p_orderid,ctx."TenantId",ctx."BranchId",ctx."TableId",customer_id,p_customername,p_customerwhatsapp,p_notes,subtotal,offer_id,offer_title,discount,payable_total);
    INSERT INTO "OrderItems" ("OrderItemId","TenantId","BranchId","OrderId","MenuItemId","MenuItemVariantId","MenuItemName","VariantName","ItemNote","DietTypeCode","UnitPrice","Quantity","LineTotal")
    SELECT "OrderItemId",ctx."TenantId",ctx."BranchId",p_orderid,"MenuItemId","MenuItemVariantId","MenuItemName","VariantName","ItemNote","DietTypeCode","UnitPrice","Quantity","UnitPrice"*"Quantity" FROM tmp_order_items;
    INSERT INTO "OrderStatusHistory" ("OrderStatusHistoryId","TenantId","BranchId","OrderId","StatusCode") VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",p_orderid,'Placed');

    IF offer_id IS NOT NULL AND discount > 0 THEN
        INSERT INTO "BranchOfferRedemptions" ("BranchOfferRedemptionId","TenantId","BranchId","BranchOfferId","OrderId","CustomerId","CustomerWhatsApp","PromoCode","RedemptionTypeCode","SubtotalAmount","DiscountAmount","FinalTotalAmount")
        VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",offer_id,p_orderid,customer_id,p_customerwhatsapp,clean_promo,redemption_type,subtotal,discount,payable_total);
    END IF;

    RETURN QUERY SELECT * FROM public.publicorder_select(p_orderid);
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(p_qrtoken text,p_orderid uuid,p_customername text,p_customerwhatsapp text,p_notes text,p_itemsjson text,p_marketingconsent boolean,p_marketingconsentsource text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM public.publicorder_createfromqrtoken(p_qrtoken,p_orderid,p_customername,p_customerwhatsapp,p_notes,p_itemsjson,p_marketingconsent,p_marketingconsentsource,NULL);
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(p_qrtoken text,p_qrsessionid uuid,p_orderid uuid,p_customername text,p_customerwhatsapp text,p_notes text,p_itemsjson text,p_marketingconsent boolean,p_marketingconsentsource text,p_promocode text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM public.qrvisitsession_assert_active(p_qrtoken,p_qrsessionid);
    RETURN QUERY SELECT * FROM public.publicorder_createfromqrtoken(p_qrtoken,p_orderid,p_customername,p_customerwhatsapp,p_notes,p_itemsjson,p_marketingconsent,p_marketingconsentsource,p_promocode);
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(p_qrtoken text,p_qrsessionid uuid,p_orderid uuid,p_customername text,p_customerwhatsapp text,p_notes text,p_itemsjson text,p_marketingconsent boolean,p_marketingconsentsource text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
    RETURN QUERY SELECT * FROM public.publicorder_createfromqrtoken(p_qrtoken,p_qrsessionid,p_orderid,p_customername,p_customerwhatsapp,p_notes,p_itemsjson,p_marketingconsent,p_marketingconsentsource,NULL);
END;
$$;
