CREATE TABLE IF NOT EXISTS "OrderItemCancellationRequests" (
    "OrderItemCancellationRequestId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId"),
    "OrderItemId" uuid NOT NULL REFERENCES "OrderItems" ("OrderItemId"),
    "RequestedQuantity" integer NOT NULL CHECK ("RequestedQuantity" > 0),
    "Reason" varchar(300) NOT NULL,
    "StatusCode" varchar(32) NOT NULL DEFAULT 'Pending',
    "RequestedAtUtc" timestamptz NOT NULL DEFAULT public.app_now(),
    "RespondedAtUtc" timestamptz NULL,
    "RespondedByUserId" uuid NULL REFERENCES "Users" ("UserId"),
    "ResponseReason" varchar(300) NULL,
    CONSTRAINT "CK_OrderItemCancellationRequests_StatusCode" CHECK ("StatusCode" IN ('Pending','Approved','Rejected'))
);

CREATE UNIQUE INDEX IF NOT EXISTS "UX_OrderItemCancellationRequests_PendingItem"
ON "OrderItemCancellationRequests" ("TenantId","BranchId","OrderItemId")
WHERE "StatusCode" = 'Pending';

DROP FUNCTION IF EXISTS public.publicorder_getitemsbyorder(uuid);
CREATE OR REPLACE FUNCTION public.publicorder_getitemsbyorder(p_orderid uuid)
RETURNS TABLE("OrderItemId" uuid,"OrderId" uuid,"MenuItemId" uuid,"MenuItemVariantId" uuid,"MenuItemName" varchar,"VariantName" varchar,"ItemNote" varchar,"DietTypeCode" varchar,"UnitPrice" numeric,"Quantity" integer,"LineTotal" numeric,"PendingCancellationRequestId" uuid,"PendingCancellationQuantity" integer,"PendingCancellationReason" varchar,"PendingCancellationRequestedAtUtc" timestamptz)
LANGUAGE sql STABLE AS $$
    SELECT oi."OrderItemId",
           oi."OrderId",
           oi."MenuItemId",
           oi."MenuItemVariantId",
           oi."MenuItemName",
           oi."VariantName",
           oi."ItemNote",
           oi."DietTypeCode",
           oi."UnitPrice",
           (oi."Quantity" - oi."CancelledQuantity")::integer,
           round(oi."UnitPrice" * (oi."Quantity" - oi."CancelledQuantity"),2),
           req."OrderItemCancellationRequestId",
           req."RequestedQuantity",
           req."Reason",
           req."RequestedAtUtc"
    FROM "OrderItems" oi
    LEFT JOIN "OrderItemCancellationRequests" req ON req."OrderItemId"=oi."OrderItemId" AND req."StatusCode"='Pending'
    WHERE oi."OrderId"=p_orderid
      AND (oi."Quantity" - oi."CancelledQuantity") > 0
    ORDER BY oi."RowId";
$$;

DROP FUNCTION IF EXISTS public.adminorder_getitemsbybranch(uuid,uuid);
CREATE OR REPLACE FUNCTION public.adminorder_getitemsbybranch(p_tenantid uuid,p_branchid uuid)
RETURNS TABLE("OrderItemId" uuid,"OrderId" uuid,"MenuItemId" uuid,"MenuItemVariantId" uuid,"MenuItemName" varchar,"VariantName" varchar,"ItemNote" varchar,"DietTypeCode" varchar,"UnitPrice" numeric,"Quantity" integer,"LineTotal" numeric,"CancelledQuantity" integer,"ActiveQuantity" integer,"ActiveLineTotal" numeric,"CancelledReason" varchar,"CancelledAtUtc" timestamptz,"PendingCancellationRequestId" uuid,"PendingCancellationQuantity" integer,"PendingCancellationReason" varchar,"PendingCancellationRequestedAtUtc" timestamptz)
LANGUAGE sql STABLE AS $$
    SELECT oi."OrderItemId",
           oi."OrderId",
           oi."MenuItemId",
           oi."MenuItemVariantId",
           oi."MenuItemName",
           oi."VariantName",
           oi."ItemNote",
           oi."DietTypeCode",
           oi."UnitPrice",
           oi."Quantity",
           oi."LineTotal",
           oi."CancelledQuantity",
           (oi."Quantity" - oi."CancelledQuantity")::integer,
           round(oi."UnitPrice" * (oi."Quantity" - oi."CancelledQuantity"),2),
           oi."CancelledReason",
           oi."CancelledAtUtc",
           req."OrderItemCancellationRequestId",
           req."RequestedQuantity",
           req."Reason",
           req."RequestedAtUtc"
    FROM "OrderItems" oi
    JOIN "Orders" o ON o."OrderId"=oi."OrderId"
    LEFT JOIN "OrderItemCancellationRequests" req ON req."OrderItemId"=oi."OrderItemId" AND req."StatusCode"='Pending'
    WHERE oi."TenantId"=p_tenantid AND oi."BranchId"=p_branchid
    ORDER BY oi."RowId";
$$;

CREATE OR REPLACE FUNCTION public.publicorder_requestitemcancellation(p_qrtoken text,p_orderid uuid,p_orderitemid uuid,p_cancelquantity integer,p_reason text,p_tokenhash text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
DECLARE
    ctx record;
    item_row record;
    pending_quantity integer := 0;
BEGIN
    SELECT o."OrderId",o."TenantId",o."BranchId",o."TableId",o."CustomerId",o."OrderStatusCode"
    INTO ctx
    FROM "Orders" o
    JOIN "BranchTables" bt ON bt."TableId"=o."TableId" AND bt."BranchId"=o."BranchId" AND bt."TenantId"=o."TenantId" AND bt."QrToken"=p_qrtoken AND bt."IsActive"
    JOIN "Branches" b ON b."BranchId"=o."BranchId" AND b."TenantId"=o."TenantId" AND b."IsActive"
    WHERE o."OrderId"=p_orderid AND public.tenant_public_access_allowed(o."TenantId")
    FOR UPDATE;

    IF ctx."OrderId" IS NULL THEN PERFORM public.raise_app_error(51709); END IF;
    IF ctx."CustomerId" IS NULL OR NOT EXISTS (
        SELECT 1 FROM "CustomerDeviceAccessTokens" access
        WHERE access."TenantId"=ctx."TenantId" AND access."BranchId"=ctx."BranchId" AND access."CustomerId"=ctx."CustomerId"
          AND access."TokenHash"=p_tokenhash AND access."RevokedAtUtc" IS NULL AND access."ExpiresAtUtc" > public.app_now()
    ) THEN
        PERFORM public.raise_app_error(51716);
    END IF;
    IF ctx."OrderStatusCode" NOT IN ('Placed','Accepted','Preparing') THEN PERFORM public.raise_app_error(51717); END IF;
    IF EXISTS (
        SELECT 1 FROM "OrderBills" ob
        WHERE ob."TenantId"=ctx."TenantId" AND ob."BranchId"=ctx."BranchId" AND ob."OrderId"=p_orderid AND ob."PaymentStatusCode" <> 'Unpaid'
    ) THEN
        PERFORM public.raise_app_error(51714);
    END IF;
    IF COALESCE(p_cancelquantity,0) <= 0 THEN PERFORM public.raise_app_error(51711); END IF;
    IF NULLIF(btrim(p_reason),'') IS NULL OR length(btrim(p_reason)) > 300 THEN PERFORM public.raise_app_error(51712); END IF;

    SELECT oi.* INTO item_row
    FROM "OrderItems" oi
    WHERE oi."TenantId"=ctx."TenantId" AND oi."BranchId"=ctx."BranchId" AND oi."OrderId"=p_orderid AND oi."OrderItemId"=p_orderitemid
    FOR UPDATE;
    IF item_row."OrderItemId" IS NULL THEN PERFORM public.raise_app_error(51713); END IF;

    SELECT COALESCE(SUM(req."RequestedQuantity"),0)::integer
    INTO pending_quantity
    FROM "OrderItemCancellationRequests" req
    WHERE req."OrderItemId"=p_orderitemid AND req."StatusCode"='Pending';

    IF p_cancelquantity > (item_row."Quantity" - item_row."CancelledQuantity" + pending_quantity) THEN
        PERFORM public.raise_app_error(51711);
    END IF;

    INSERT INTO "OrderItemCancellationRequests" ("OrderItemCancellationRequestId","TenantId","BranchId","OrderId","OrderItemId","RequestedQuantity","Reason")
    VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",p_orderid,p_orderitemid,p_cancelquantity,btrim(p_reason))
    ON CONFLICT ("TenantId","BranchId","OrderItemId") WHERE "StatusCode"='Pending'
    DO UPDATE SET "RequestedQuantity"=EXCLUDED."RequestedQuantity","Reason"=EXCLUDED."Reason","RequestedAtUtc"=public.app_now();

    RETURN QUERY SELECT * FROM public.publicorder_select(p_orderid);
END;
$$;

CREATE OR REPLACE FUNCTION public.adminorder_responditemcancellationrequest(p_tenantid uuid,p_branchid uuid,p_requestid uuid,p_decision text,p_reason text,p_changedbyuserid uuid)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"TableName" varchar,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz,"ClosedAtUtc" timestamptz,"LatestReason" varchar)
LANGUAGE plpgsql AS $$
DECLARE
    req record;
BEGIN
    SELECT * INTO req
    FROM "OrderItemCancellationRequests"
    WHERE "TenantId"=p_tenantid AND "BranchId"=p_branchid AND "OrderItemCancellationRequestId"=p_requestid
    FOR UPDATE;

    IF req."OrderItemCancellationRequestId" IS NULL THEN PERFORM public.raise_app_error(51718); END IF;
    IF req."StatusCode" <> 'Pending' THEN PERFORM public.raise_app_error(51715); END IF;
    IF p_decision NOT IN ('Approved','Rejected') THEN PERFORM public.raise_app_error(51719); END IF;
    IF p_decision='Rejected' AND NULLIF(btrim(p_reason),'') IS NULL THEN PERFORM public.raise_app_error(51712); END IF;
    IF length(COALESCE(btrim(p_reason),'')) > 300 THEN PERFORM public.raise_app_error(51712); END IF;

    IF p_decision='Approved' THEN
        PERFORM * FROM public.adminorder_cancelitem(p_tenantid,p_branchid,req."OrderId",req."OrderItemId",req."RequestedQuantity",req."Reason",p_changedbyuserid);
    END IF;

    UPDATE "OrderItemCancellationRequests"
    SET "StatusCode"=p_decision,
        "RespondedAtUtc"=public.app_now(),
        "RespondedByUserId"=p_changedbyuserid,
        "ResponseReason"=NULLIF(btrim(p_reason),'')
    WHERE "OrderItemCancellationRequestId"=p_requestid;

    RETURN QUERY SELECT * FROM public.adminorder_getlistbybranch(p_tenantid,p_branchid,true) a WHERE a."OrderId"=req."OrderId";
END;
$$;
