using Npgsql;

namespace QRApp.Api.Database;

public static class DatabaseStartupPatches
{
    public static async Task ApplyDatabaseStartupPatchesAsync(this WebApplication app)
    {
        var connectionString = app.Configuration.GetConnectionString("Postgres");
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return;
        }

        var builder = new NpgsqlConnectionStringBuilder(connectionString);
        if (string.IsNullOrWhiteSpace(builder.Timezone))
        {
            builder.Timezone = "Asia/Kolkata";
        }

        var logger = app.Services.GetRequiredService<ILoggerFactory>().CreateLogger("DatabaseStartupPatches");
        await using var connection = new NpgsqlConnection(builder.ConnectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(PublicOrderSql, connection);
        await command.ExecuteNonQueryAsync();

        await using var orderItemCancellationCommand = new NpgsqlCommand(OrderItemCancellationSql, connection);
        await orderItemCancellationCommand.ExecuteNonQueryAsync();

        logger.LogInformation("Applied database startup patches.");
    }

    private const string PublicOrderSql = """
ALTER TABLE "MenuItems"
ADD COLUMN IF NOT EXISTS "DietTypeCode" varchar(32) NOT NULL DEFAULT 'Unspecified';

ALTER TABLE "OrderItems"
ADD COLUMN IF NOT EXISTS "DietTypeCode" varchar(32) NOT NULL DEFAULT 'Unspecified';

CREATE TABLE IF NOT EXISTS "QrVisitSessions" (
    "QrSessionId" uuid PRIMARY KEY,
    "TenantId" uuid NOT NULL REFERENCES "Tenants"("TenantId") ON DELETE CASCADE,
    "BranchId" uuid NOT NULL REFERENCES "Branches"("BranchId") ON DELETE CASCADE,
    "TableId" uuid NOT NULL REFERENCES "BranchTables"("TableId") ON DELETE CASCADE,
    "QrToken" varchar(80) NOT NULL,
    "StartedAtUtc" timestamptz NOT NULL DEFAULT public.app_now(),
    "ExpiresAtUtc" timestamptz NOT NULL,
    "RevokedAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now()
);

CREATE INDEX IF NOT EXISTS "IX_QrVisitSessions_QrToken_ExpiresAtUtc" ON "QrVisitSessions" ("QrToken","ExpiresAtUtc");

CREATE TABLE IF NOT EXISTS "SuperAdminUsers" (
    "SuperAdminUserId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email" varchar(256) NOT NULL,
    "DisplayName" varchar(160) NOT NULL,
    "PasswordHash" varchar(512) NOT NULL,
    "RoleCode" varchar(40) NOT NULL DEFAULT 'super_admin',
    "IsActive" boolean NOT NULL DEFAULT true,
    "LastLoginAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now(),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_SuperAdminUsers_Email" UNIQUE ("Email"),
    CONSTRAINT "CK_SuperAdminUsers_RoleCode" CHECK ("RoleCode" IN ('super_admin', 'support_admin', 'sales_admin'))
);

CREATE TABLE IF NOT EXISTS "SuperAdminAuditEntries" (
    "SuperAdminAuditEntryId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NULL REFERENCES "Tenants" ("TenantId"),
    "SuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "ActionCode" varchar(80) NOT NULL,
    "Summary" varchar(500) NOT NULL,
    "MetadataJson" text NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now()
);

CREATE TABLE IF NOT EXISTS "SuperAdminInternalNotes" (
    "SuperAdminInternalNoteId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId") ON DELETE CASCADE,
    "Note" varchar(1000) NOT NULL,
    "CreatedBySuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now()
);

CREATE INDEX IF NOT EXISTS "IX_SuperAdminAuditEntries_TenantId_CreatedAtUtc" ON "SuperAdminAuditEntries" ("TenantId", "CreatedAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_SuperAdminAuditEntries_CreatedAtUtc" ON "SuperAdminAuditEntries" ("CreatedAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_SuperAdminInternalNotes_TenantId_CreatedAtUtc" ON "SuperAdminInternalNotes" ("TenantId", "CreatedAtUtc" DESC);

ALTER TABLE "AdminNotifications"
ADD COLUMN IF NOT EXISTS "TargetUrl" varchar(500) NOT NULL DEFAULT '/admin';

DROP FUNCTION IF EXISTS public.publicorder_getitemsbyorder(uuid);

CREATE OR REPLACE FUNCTION public.tenant_public_access_allowed(p_tenantid uuid)
RETURNS boolean
LANGUAGE sql STABLE AS $$
    SELECT COALESCE((
        SELECT t."IsActive"
           AND t."AccountStatusCode" = 'Active'
           AND (
                t."SubscriptionStatusCode" IN ('Active','ManualActive')
                OR (
                    t."SubscriptionStatusCode" = 'Trialing'
                    AND (t."TrialStartAtUtc" IS NULL OR t."TrialStartAtUtc" <= public.app_now())
                    AND t."TrialEndAtUtc" IS NOT NULL
                    AND t."TrialEndAtUtc" >= public.app_now()
                )
           )
        FROM "Tenants" t
        WHERE t."TenantId" = p_tenantid
    ), false);
$$;

CREATE OR REPLACE FUNCTION public.publicqr_assert_tenant_available(p_qrtoken text)
RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    tenant_id uuid;
BEGIN
    SELECT bt."TenantId"
    INTO tenant_id
    FROM "BranchTables" bt
    WHERE bt."QrToken" = p_qrtoken AND bt."IsActive"
    LIMIT 1;

    IF tenant_id IS NOT NULL AND NOT public.tenant_public_access_allowed(tenant_id) THEN
        PERFORM public.raise_app_error(52002);
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.qrvisitsession_create(p_qrtoken text,p_qrsessionid uuid,p_ttlminutes integer)
RETURNS TABLE("QrSessionId" uuid,"BranchId" uuid,"TableId" uuid,"StartedAtUtc" timestamptz,"ExpiresAtUtc" timestamptz,"IsExpired" boolean)
LANGUAGE plpgsql AS $$
DECLARE
    ctx record;
    started_at timestamptz := public.app_now();
    ttl_minutes integer := LEAST(GREATEST(COALESCE(p_ttlminutes,240),15),720);
BEGIN
    PERFORM public.publicqr_assert_tenant_available(p_qrtoken);

    SELECT bt."TenantId",bt."BranchId",bt."TableId"
    INTO ctx
    FROM "BranchTables" bt
    JOIN "Branches" b ON b."BranchId"=bt."BranchId" AND b."IsActive"
    WHERE bt."QrToken"=p_qrtoken AND bt."IsActive";

    IF ctx."TableId" IS NULL THEN
        PERFORM public.raise_app_error(51701);
    END IF;

    INSERT INTO "QrVisitSessions" ("QrSessionId","TenantId","BranchId","TableId","QrToken","StartedAtUtc","ExpiresAtUtc")
    VALUES (p_qrsessionid,ctx."TenantId",ctx."BranchId",ctx."TableId",p_qrtoken,started_at,started_at + make_interval(mins => ttl_minutes));

    RETURN QUERY
    SELECT qvs."QrSessionId",qvs."BranchId",qvs."TableId",qvs."StartedAtUtc",qvs."ExpiresAtUtc",(qvs."ExpiresAtUtc" <= public.app_now() OR qvs."RevokedAtUtc" IS NOT NULL)
    FROM "QrVisitSessions" qvs
    WHERE qvs."QrSessionId"=p_qrsessionid;
END;
$$;

CREATE OR REPLACE FUNCTION public.qrvisitsession_assert_active(p_qrtoken text,p_qrsessionid uuid)
RETURNS TABLE("TenantId" uuid,"BranchId" uuid,"TableId" uuid)
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM public.publicqr_assert_tenant_available(p_qrtoken);

    RETURN QUERY
    SELECT qvs."TenantId",qvs."BranchId",qvs."TableId"
    FROM "QrVisitSessions" qvs
    JOIN "BranchTables" bt ON bt."TableId"=qvs."TableId" AND bt."QrToken"=p_qrtoken AND bt."IsActive"
    JOIN "Branches" b ON b."BranchId"=qvs."BranchId" AND b."IsActive"
    WHERE qvs."QrSessionId"=p_qrsessionid
      AND qvs."QrToken"=p_qrtoken
      AND qvs."RevokedAtUtc" IS NULL
      AND qvs."ExpiresAtUtc" > public.app_now();

    IF NOT FOUND THEN
        PERFORM public.raise_app_error(52001);
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_select(p_orderid uuid)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE sql STABLE AS $$ SELECT o."OrderId",o."TenantId",o."BranchId",o."TableId",o."OrderStatusCode",o."CustomerName",o."CustomerWhatsApp",o."Notes",o."SubtotalAmount",o."TotalAmount",o."AppliedBranchOfferId",o."AppliedOfferTitle",o."AppliedOfferDiscountAmount",o."CreatedAtUtc",o."UpdatedAtUtc" FROM "Orders" o WHERE o."OrderId"=p_orderid; $$;

CREATE OR REPLACE FUNCTION public.publicorder_getitemsbyorder(p_orderid uuid)
RETURNS TABLE("OrderItemId" uuid,"OrderId" uuid,"MenuItemId" uuid,"MenuItemVariantId" uuid,"MenuItemName" varchar,"VariantName" varchar,"ItemNote" varchar,"DietTypeCode" varchar,"UnitPrice" numeric,"Quantity" integer,"LineTotal" numeric)
LANGUAGE sql STABLE AS $$ SELECT oi."OrderItemId",oi."OrderId",oi."MenuItemId",oi."MenuItemVariantId",oi."MenuItemName",oi."VariantName",oi."ItemNote",oi."DietTypeCode",oi."UnitPrice",oi."Quantity",oi."LineTotal" FROM "OrderItems" oi WHERE oi."OrderId"=p_orderid ORDER BY oi."RowId"; $$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(p_qrtoken text,p_orderid uuid,p_customername text,p_customerwhatsapp text,p_notes text,p_itemsjson text,p_marketingconsent boolean,p_marketingconsentsource text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
DECLARE
    ctx record;
    customer_id uuid;
    subtotal numeric;
    billing record;
    offer_id uuid;
    offer_title varchar;
    discount numeric := 0;
    taxable numeric := 0;
    tax numeric := 0;
    service_charge numeric := 0;
    total_before_rounding numeric := 0;
    rounding_amount numeric := 0;
    payable_total numeric := 0;
BEGIN
    SELECT bt."TenantId",bt."BranchId",bt."TableId",COALESCE(bos."EnableDirectQrOrdering",false) enabled,COALESCE(bos."RequireCustomerName",false) req_name,COALESCE(bos."RequireCustomerWhatsApp",false) req_whatsapp
    INTO ctx FROM "BranchTables" bt JOIN "Branches" b ON b."BranchId"=bt."BranchId" AND b."IsActive" LEFT JOIN "BranchOrderSettings" bos ON bos."BranchId"=bt."BranchId" WHERE bt."QrToken"=p_qrtoken AND bt."IsActive";
    IF ctx."TableId" IS NULL THEN PERFORM public.raise_app_error(51701); END IF;
    IF NOT ctx.enabled THEN PERFORM public.raise_app_error(51702); END IF;
    IF ctx.req_name AND NULLIF(btrim(p_customername),'') IS NULL THEN PERFORM public.raise_app_error(51703); END IF;
    IF ctx.req_whatsapp AND NULLIF(btrim(p_customerwhatsapp),'') IS NULL THEN PERFORM public.raise_app_error(51704); END IF;

    CREATE TEMP TABLE tmp_order_items ON COMMIT DROP AS
    SELECT gen_random_uuid() "OrderItemId", mi."MenuItemId", v."MenuItemVariantId", mi."Name" "MenuItemName", v."Name" "VariantName", NULLIF(x->>'itemNote','') "ItemNote", mi."DietTypeCode", COALESCE(v."Price",mi."Price") "UnitPrice", GREATEST(COALESCE((x->>'quantity')::integer,0),0) "Quantity"
    FROM jsonb_array_elements(COALESCE(NULLIF(p_itemsjson,'')::jsonb,'[]'::jsonb)) x
    JOIN "MenuItems" mi ON mi."MenuItemId"=(x->>'menuItemId')::uuid AND mi."TenantId"=ctx."TenantId" AND mi."BranchId"=ctx."BranchId" AND mi."IsActive" AND mi."IsAvailable"
    LEFT JOIN "MenuItemVariants" v ON v."MenuItemVariantId"=NULLIF(x->>'menuItemVariantId','')::uuid AND v."MenuItemId"=mi."MenuItemId" AND v."IsAvailable";
    DELETE FROM tmp_order_items WHERE "Quantity" <= 0;
    IF NOT EXISTS (SELECT 1 FROM tmp_order_items) THEN PERFORM public.raise_app_error(51705); END IF;
    SELECT SUM("UnitPrice"*"Quantity") INTO subtotal FROM tmp_order_items;

    IF NULLIF(btrim(p_customerwhatsapp),'') IS NOT NULL THEN
        INSERT INTO "Customers" ("CustomerId","TenantId","BranchId","Name","WhatsAppNumber","VisitCount","LastVisitAtUtc","MarketingConsent","MarketingConsentSource","MarketingConsentAtUtc")
        VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",COALESCE(NULLIF(p_customername,''),'Guest'),p_customerwhatsapp,1,public.app_now(),p_marketingconsent,p_marketingconsentsource,CASE WHEN p_marketingconsent THEN public.app_now() END)
        ON CONFLICT ON CONSTRAINT "UQ_Customers_TenantId_BranchId_WhatsAppNumber" DO UPDATE SET "Name"=COALESCE(NULLIF(EXCLUDED."Name",''),"Customers"."Name"),"VisitCount"="Customers"."VisitCount"+1,"LastVisitAtUtc"=public.app_now(),"MarketingConsent"=("Customers"."MarketingConsent" OR EXCLUDED."MarketingConsent"),"UpdatedAtUtc"=public.app_now()
        RETURNING "CustomerId" INTO customer_id;
    END IF;

    SELECT
        COALESCE(bs."TaxEnabled",false) "TaxEnabled",
        COALESCE(bs."TaxRate",0) "TaxRate",
        COALESCE(bs."TaxMode",'Exclusive') "TaxMode",
        COALESCE(bs."ServiceChargeEnabled",false) "ServiceChargeEnabled",
        COALESCE(bs."ServiceChargeRate",0) "ServiceChargeRate",
        COALESCE(bs."RoundingMode",'None') "RoundingMode"
    INTO billing
    FROM "Branches" b
    LEFT JOIN "BranchBillingSettings" bs ON bs."TenantId"=b."TenantId" AND bs."BranchId"=b."BranchId"
    WHERE b."TenantId"=ctx."TenantId" AND b."BranchId"=ctx."BranchId";

    SELECT selected_offer."BranchOfferId", selected_offer."Title", selected_offer.computed_discount
    INTO offer_id, offer_title, discount
    FROM (
        SELECT bo.*,
               round(LEAST(
                   subtotal,
                   GREATEST(
                       0,
                       CASE
                           WHEN bo."MaxDiscountAmount" IS NOT NULL THEN LEAST(
                               CASE bo."DiscountTypeCode"
                                   WHEN 'Percentage' THEN round(subtotal * bo."DiscountValue" / 100,2)
                                   ELSE round(bo."DiscountValue",2)
                               END,
                               bo."MaxDiscountAmount"
                           )
                           ELSE CASE bo."DiscountTypeCode"
                               WHEN 'Percentage' THEN round(subtotal * bo."DiscountValue" / 100,2)
                               ELSE round(bo."DiscountValue",2)
                           END
                       END
                   )
               ),2) AS computed_discount
        FROM "BranchOffers" bo
        WHERE bo."TenantId"=ctx."TenantId"
          AND bo."BranchId"=ctx."BranchId"
          AND bo."IsActive"
          AND bo."AutoApply"
          AND bo."DiscountTypeCode" <> 'DisplayOnly'
          AND bo."DiscountValue" > 0
          AND subtotal >= bo."MinimumOrderAmount"
          AND (bo."StartsAtUtc" IS NULL OR bo."StartsAtUtc" <= public.app_now())
          AND (bo."EndsAtUtc" IS NULL OR bo."EndsAtUtc" >= public.app_now())
        ORDER BY computed_discount DESC, bo."DisplayOrder", bo."Title"
        LIMIT 1
    ) selected_offer;
    discount := COALESCE(discount,0);

    taxable := round(GREATEST(subtotal - discount,0),2);
    IF billing."TaxEnabled" AND billing."TaxRate" > 0 THEN
        tax := CASE
            WHEN billing."TaxMode" = 'Inclusive' THEN round(taxable - taxable / (1 + billing."TaxRate" / 100),2)
            ELSE round(taxable * billing."TaxRate" / 100,2)
        END;
    END IF;
    IF billing."ServiceChargeEnabled" AND billing."ServiceChargeRate" > 0 THEN
        service_charge := round(taxable * billing."ServiceChargeRate" / 100,2);
    END IF;
    total_before_rounding := round((CASE WHEN billing."TaxMode" = 'Inclusive' THEN taxable ELSE taxable + tax END) + service_charge,2);
    rounding_amount := CASE WHEN billing."RoundingMode" IN ('NearestRupee','Nearest') THEN round(total_before_rounding) - total_before_rounding ELSE 0 END;
    payable_total := round(total_before_rounding + rounding_amount,2);

    INSERT INTO "Orders" ("OrderId","TenantId","BranchId","TableId","CustomerId","CustomerName","CustomerWhatsApp","Notes","SubtotalAmount","AppliedBranchOfferId","AppliedOfferTitle","AppliedOfferDiscountAmount","TotalAmount")
    VALUES (p_orderid,ctx."TenantId",ctx."BranchId",ctx."TableId",customer_id,p_customername,p_customerwhatsapp,p_notes,subtotal,offer_id,offer_title,discount,payable_total);
    INSERT INTO "OrderItems" ("OrderItemId","TenantId","BranchId","OrderId","MenuItemId","MenuItemVariantId","MenuItemName","VariantName","ItemNote","DietTypeCode","UnitPrice","Quantity","LineTotal")
    SELECT "OrderItemId",ctx."TenantId",ctx."BranchId",p_orderid,"MenuItemId","MenuItemVariantId","MenuItemName","VariantName","ItemNote","DietTypeCode","UnitPrice","Quantity","UnitPrice"*"Quantity" FROM tmp_order_items;
    INSERT INTO "OrderStatusHistory" ("OrderStatusHistoryId","TenantId","BranchId","OrderId","StatusCode") VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",p_orderid,'Placed');
    RETURN QUERY SELECT * FROM public.publicorder_select(p_orderid);
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(p_qrtoken text,p_qrsessionid uuid,p_orderid uuid,p_customername text,p_customerwhatsapp text,p_notes text,p_itemsjson text,p_marketingconsent boolean,p_marketingconsentsource text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM public.qrvisitsession_assert_active(p_qrtoken,p_qrsessionid);
    RETURN QUERY SELECT * FROM public.publicorder_createfromqrtoken(p_qrtoken,p_orderid,p_customername,p_customerwhatsapp,p_notes,p_itemsjson,p_marketingconsent,p_marketingconsentsource);
END;
$$;

CREATE OR REPLACE FUNCTION public.waitercall_createfromqrtoken(p_qrtoken text,p_qrsessionid uuid,p_waitercallid uuid,p_customername text,p_note text)
RETURNS TABLE("WaiterCallId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"TableName" varchar,"StatusCode" varchar,"CustomerName" varchar,"Note" varchar,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM public.qrvisitsession_assert_active(p_qrtoken,p_qrsessionid);
    RETURN QUERY SELECT * FROM public.waitercall_createfromqrtoken(p_qrtoken,p_waitercallid,p_customername,p_note);
END;
$$;

CREATE TABLE IF NOT EXISTS "OrderFeedback" (
    "OrderFeedbackId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId"),
    "BranchId" uuid NOT NULL REFERENCES "Branches" ("BranchId"),
    "OrderId" uuid NOT NULL REFERENCES "Orders" ("OrderId"),
    "Rating" integer NOT NULL CHECK ("Rating" BETWEEN 1 AND 5),
    "Comment" varchar(1000) NULL,
    "CustomerName" varchar(120) NULL,
    "CustomerWhatsApp" varchar(32) NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "UQ_OrderFeedback_OrderId" UNIQUE ("OrderId")
);

ALTER TABLE "OrderFeedback" ADD COLUMN IF NOT EXISTS "Rating" integer;
ALTER TABLE "OrderFeedback" ADD COLUMN IF NOT EXISTS "Comment" varchar(1000) NULL;
ALTER TABLE "OrderFeedback" ADD COLUMN IF NOT EXISTS "CustomerName" varchar(120) NULL;
ALTER TABLE "OrderFeedback" ADD COLUMN IF NOT EXISTS "CustomerWhatsApp" varchar(32) NULL;
ALTER TABLE "OrderFeedback" ADD COLUMN IF NOT EXISTS "CreatedAtUtc" timestamptz NOT NULL DEFAULT now();
CREATE UNIQUE INDEX IF NOT EXISTS "UX_OrderFeedback_OrderId" ON "OrderFeedback" ("OrderId");

DROP FUNCTION IF EXISTS public.orderfeedback_createfromqrtoken(text,uuid,uuid,integer,text);
DROP FUNCTION IF EXISTS public.orderfeedback_getbyqrtoken(text,uuid);

CREATE OR REPLACE FUNCTION public.orderfeedback_createfromqrtoken(
    p_qrtoken text,
    p_orderid uuid,
    p_orderfeedbackid uuid,
    p_rating integer,
    p_comment text
)
RETURNS TABLE(
    "OrderFeedbackId" uuid,
    "TenantId" uuid,
    "BranchId" uuid,
    "OrderId" uuid,
    "CustomerId" uuid,
    "Rating" integer,
    "Comment" varchar,
    "CreatedAtUtc" timestamptz
)
LANGUAGE plpgsql AS $$
DECLARE
    order_context record;
BEGIN
    SELECT
        o."TenantId",
        o."BranchId",
        o."OrderId",
        o."CustomerId",
        o."CustomerName",
        o."CustomerWhatsApp"
    INTO order_context
    FROM "Orders" o
    JOIN "BranchTables" bt ON bt."TableId" = o."TableId"
    WHERE o."OrderId" = p_orderid
      AND bt."QrToken" = p_qrtoken;

    IF NOT FOUND THEN
        PERFORM public.raise_app_error(51709);
    END IF;

    RETURN QUERY
    WITH saved AS (
        INSERT INTO "OrderFeedback" (
            "OrderFeedbackId",
            "TenantId",
            "BranchId",
            "OrderId",
            "Rating",
            "Comment",
            "CustomerName",
            "CustomerWhatsApp"
        )
        VALUES (
            p_orderfeedbackid,
            order_context."TenantId",
            order_context."BranchId",
            p_orderid,
            p_rating,
            p_comment,
            order_context."CustomerName",
            order_context."CustomerWhatsApp"
        )
        ON CONFLICT ("OrderId") DO UPDATE SET
            "Rating" = EXCLUDED."Rating",
            "Comment" = EXCLUDED."Comment",
            "CustomerName" = EXCLUDED."CustomerName",
            "CustomerWhatsApp" = EXCLUDED."CustomerWhatsApp"
        RETURNING *
    )
    SELECT
        saved."OrderFeedbackId",
        saved."TenantId",
        saved."BranchId",
        saved."OrderId",
        order_context."CustomerId",
        saved."Rating",
        saved."Comment",
        saved."CreatedAtUtc"
    FROM saved;
END;
$$;

CREATE OR REPLACE FUNCTION public.orderfeedback_getbyqrtoken(
    p_qrtoken text,
    p_orderid uuid
)
RETURNS TABLE(
    "OrderFeedbackId" uuid,
    "TenantId" uuid,
    "BranchId" uuid,
    "OrderId" uuid,
    "CustomerId" uuid,
    "Rating" integer,
    "Comment" varchar,
    "CreatedAtUtc" timestamptz
)
LANGUAGE sql STABLE AS $$
    SELECT
        f."OrderFeedbackId",
        f."TenantId",
        f."BranchId",
        f."OrderId",
        o."CustomerId",
        f."Rating",
        f."Comment",
        f."CreatedAtUtc"
    FROM "OrderFeedback" f
    JOIN "Orders" o ON o."OrderId" = f."OrderId"
    JOIN "BranchTables" bt ON bt."TableId" = o."TableId"
    WHERE f."OrderId" = p_orderid
      AND bt."QrToken" = p_qrtoken;
$$;

CREATE OR REPLACE FUNCTION public.publiccustomer_lookupbyqrtoken(p_qrtoken text,p_customerwhatsapp text)
RETURNS TABLE("CustomerId" uuid,"Name" varchar,"WhatsAppNumber" varchar,"MarketingConsent" boolean,"VisitCount" integer,"TotalOrderCount" integer,"TotalOrderValue" numeric,"LastVisitAtUtc" timestamptz)
LANGUAGE sql STABLE AS $$
    SELECT c."CustomerId",c."Name",c."WhatsAppNumber",c."MarketingConsent",c."VisitCount",COUNT(o."OrderId")::integer,COALESCE(SUM(o."TotalAmount"),0),COALESCE(c."LastVisitAtUtc",c."CreatedAtUtc")
    FROM "Customers" c
    JOIN "BranchTables" bt ON bt."BranchId"=c."BranchId"
    LEFT JOIN "Orders" o ON o."CustomerId"=c."CustomerId"
    WHERE bt."QrToken"=p_qrtoken
      AND public.tenant_public_access_allowed(bt."TenantId")
      AND c."WhatsAppNumber"=p_customerwhatsapp
    GROUP BY c."CustomerId";
$$;

DROP FUNCTION IF EXISTS public.adminorder_updatestatus(uuid,uuid,uuid,text,text,uuid);
DROP FUNCTION IF EXISTS public.adminorder_getlistbybranch(uuid,uuid,boolean);

CREATE OR REPLACE FUNCTION public.adminorder_getlistbybranch(p_tenantid uuid,p_branchid uuid,p_includecompleted boolean)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"TableName" varchar,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz,"ClosedAtUtc" timestamptz,"LatestReason" varchar)
LANGUAGE sql STABLE AS $$
WITH status_rollup AS (
    SELECT
        h."OrderId",
        MAX(h."CreatedAtUtc") FILTER (WHERE h."StatusCode" IN ('Completed','Cancelled')) AS "ClosedAtUtc"
    FROM "OrderStatusHistory" h
    WHERE h."TenantId"=p_tenantid AND h."BranchId"=p_branchid
    GROUP BY h."OrderId"
),
status_reason AS (
    SELECT DISTINCT ON (h."OrderId",h."StatusCode")
        h."OrderId",
        h."StatusCode",
        NULLIF(btrim(h."Reason"), '')::varchar AS "LatestReason"
    FROM "OrderStatusHistory" h
    WHERE h."TenantId"=p_tenantid
      AND h."BranchId"=p_branchid
      AND NULLIF(btrim(h."Reason"), '') IS NOT NULL
    ORDER BY h."OrderId",h."StatusCode",h."CreatedAtUtc" DESC
)
SELECT
    o."OrderId",
    o."TenantId",
    o."BranchId",
    o."TableId",
    bt."Name",
    o."OrderStatusCode",
    o."CustomerName",
    o."CustomerWhatsApp",
    o."Notes",
    o."SubtotalAmount",
    o."TotalAmount",
    o."AppliedBranchOfferId",
    o."AppliedOfferTitle",
    o."AppliedOfferDiscountAmount",
    o."CreatedAtUtc",
    o."UpdatedAtUtc",
    sr."ClosedAtUtc",
    latest_reason."LatestReason"
FROM "Orders" o
JOIN "BranchTables" bt ON bt."TableId"=o."TableId"
LEFT JOIN status_rollup sr ON sr."OrderId"=o."OrderId"
LEFT JOIN status_reason latest_reason ON latest_reason."OrderId"=o."OrderId" AND latest_reason."StatusCode"=o."OrderStatusCode"
WHERE o."TenantId"=p_tenantid
  AND o."BranchId"=p_branchid
  AND (p_includecompleted OR o."OrderStatusCode" NOT IN ('Completed','Cancelled','Served'))
ORDER BY CASE WHEN o."OrderStatusCode" IN ('Completed','Cancelled') THEN 1 ELSE 0 END,
         COALESCE(sr."ClosedAtUtc",o."CreatedAtUtc") DESC,
         o."CreatedAtUtc" DESC
LIMIT 500;
$$;

CREATE OR REPLACE FUNCTION public.adminorder_updatestatus(p_tenantid uuid,p_branchid uuid,p_orderid uuid,p_orderstatuscode text,p_reason text,p_changedbyuserid uuid)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"TableName" varchar,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz,"ClosedAtUtc" timestamptz,"LatestReason" varchar)
LANGUAGE plpgsql AS $$
DECLARE old_status text;
BEGIN
    IF p_orderstatuscode NOT IN ('Placed','Accepted','Preparing','Ready','Served','Completed','Cancelled','Void') THEN
        PERFORM public.raise_app_error(51707);
    END IF;

    SELECT o."OrderStatusCode"
    INTO old_status
    FROM "Orders" o
    WHERE o."TenantId"=p_tenantid AND o."BranchId"=p_branchid AND o."OrderId"=p_orderid;

    IF old_status IS NULL THEN
        PERFORM public.raise_app_error(51708);
    END IF;

    UPDATE "Orders" o
    SET "OrderStatusCode"=p_orderstatuscode,
        "UpdatedAtUtc"=public.app_now()
    WHERE o."OrderId"=p_orderid;

    INSERT INTO "OrderStatusHistory" ("OrderStatusHistoryId","TenantId","BranchId","OrderId","StatusCode","Reason","ChangedByUserId")
    VALUES (gen_random_uuid(),p_tenantid,p_branchid,p_orderid,p_orderstatuscode,p_reason,p_changedbyuserid);

    RETURN QUERY
    SELECT a.*
    FROM public.adminorder_getlistbybranch(p_tenantid,p_branchid,true) a
    WHERE a."OrderId"=p_orderid;
END;
$$;

CREATE OR REPLACE FUNCTION public.report_orders(p_tenantid uuid,p_branchid uuid,p_datefrom timestamptz,p_dateto timestamptz,p_statuscode text,p_search text)
RETURNS TABLE("OrderId" uuid,"BranchId" uuid,"BranchName" varchar,"TableId" uuid,"TableName" varchar,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"TotalAmount" numeric,"ItemCount" integer,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz,"AcceptedAtUtc" timestamptz,"PreparingAtUtc" timestamptz,"ReadyAtUtc" timestamptz,"ServedAtUtc" timestamptz,"CompletedAtUtc" timestamptz,"CancelledAtUtc" timestamptz,"LatestReason" varchar)
LANGUAGE sql STABLE AS $$
WITH status_rollup AS (
    SELECT
        h."OrderId",
        MIN(h."CreatedAtUtc") FILTER (WHERE h."StatusCode"='Accepted') AS "AcceptedAtUtc",
        MIN(h."CreatedAtUtc") FILTER (WHERE h."StatusCode"='Preparing') AS "PreparingAtUtc",
        MIN(h."CreatedAtUtc") FILTER (WHERE h."StatusCode"='Ready') AS "ReadyAtUtc",
        MIN(h."CreatedAtUtc") FILTER (WHERE h."StatusCode"='Served') AS "ServedAtUtc",
        MIN(h."CreatedAtUtc") FILTER (WHERE h."StatusCode"='Completed') AS "CompletedAtUtc",
        MAX(h."CreatedAtUtc") FILTER (WHERE h."StatusCode" IN ('Cancelled','Void')) AS "CancelledAtUtc"
    FROM "OrderStatusHistory" h
    WHERE h."TenantId"=p_tenantid
    GROUP BY h."OrderId"
),
status_reason AS (
    SELECT DISTINCT ON (h."OrderId",h."StatusCode")
        h."OrderId",
        h."StatusCode",
        NULLIF(btrim(h."Reason"), '')::varchar AS "LatestReason"
    FROM "OrderStatusHistory" h
    WHERE h."TenantId"=p_tenantid
      AND (p_branchid IS NULL OR h."BranchId"=p_branchid)
      AND NULLIF(btrim(h."Reason"), '') IS NOT NULL
    ORDER BY h."OrderId",h."StatusCode",h."CreatedAtUtc" DESC
),
base_orders AS (
    SELECT
        o."OrderId",
        o."BranchId",
        b."Name" AS "BranchName",
        o."TableId",
        bt."Name" AS "TableName",
        o."OrderStatusCode",
        o."CustomerName",
        o."CustomerWhatsApp",
        o."Notes",
        o."TotalAmount",
        o."CreatedAtUtc",
        o."UpdatedAtUtc",
        sr."AcceptedAtUtc",
        sr."PreparingAtUtc",
        sr."ReadyAtUtc",
        sr."ServedAtUtc",
        sr."CompletedAtUtc",
        sr."CancelledAtUtc",
        latest_reason."LatestReason",
        CASE
            WHEN lower(COALESCE(p_statuscode,'')) IN ('cancelled','void') THEN COALESCE(sr."CancelledAtUtc",o."UpdatedAtUtc",o."CreatedAtUtc")
            WHEN lower(COALESCE(p_statuscode,''))='completed' THEN COALESCE(sr."CompletedAtUtc",o."UpdatedAtUtc",o."CreatedAtUtc")
            ELSE o."CreatedAtUtc"
        END AS "ReportAtUtc"
    FROM "Orders" o
    JOIN "Branches" b ON b."BranchId"=o."BranchId"
    JOIN "BranchTables" bt ON bt."TableId"=o."TableId"
    LEFT JOIN status_rollup sr ON sr."OrderId"=o."OrderId"
    LEFT JOIN status_reason latest_reason ON latest_reason."OrderId"=o."OrderId" AND latest_reason."StatusCode"=o."OrderStatusCode"
    WHERE o."TenantId"=p_tenantid
      AND (p_branchid IS NULL OR o."BranchId"=p_branchid)
      AND (p_statuscode IS NULL OR lower(o."OrderStatusCode")=lower(p_statuscode))
)
SELECT
    bo."OrderId",
    bo."BranchId",
    bo."BranchName",
    bo."TableId",
    bo."TableName",
    bo."OrderStatusCode",
    bo."CustomerName",
    bo."CustomerWhatsApp",
    bo."Notes",
    bo."TotalAmount",
    COUNT(oi."OrderItemId")::integer,
    bo."CreatedAtUtc",
    bo."UpdatedAtUtc",
    bo."AcceptedAtUtc",
    bo."PreparingAtUtc",
    bo."ReadyAtUtc",
    bo."ServedAtUtc",
    bo."CompletedAtUtc",
    bo."CancelledAtUtc",
    bo."LatestReason"
FROM base_orders bo
LEFT JOIN "OrderItems" oi ON oi."OrderId"=bo."OrderId"
WHERE (p_datefrom IS NULL OR bo."ReportAtUtc">=p_datefrom)
  AND (p_dateto IS NULL OR bo."ReportAtUtc"<p_dateto)
  AND (
      p_search IS NULL
      OR bo."CustomerName" ILIKE '%'||p_search||'%'
      OR bo."CustomerWhatsApp" ILIKE '%'||p_search||'%'
      OR bo."TableName" ILIKE '%'||p_search||'%'
      OR bo."OrderId"::text ILIKE '%'||p_search||'%'
  )
GROUP BY bo."OrderId",bo."BranchId",bo."BranchName",bo."TableId",bo."TableName",bo."OrderStatusCode",bo."CustomerName",bo."CustomerWhatsApp",bo."Notes",bo."TotalAmount",bo."CreatedAtUtc",bo."UpdatedAtUtc",bo."AcceptedAtUtc",bo."PreparingAtUtc",bo."ReadyAtUtc",bo."ServedAtUtc",bo."CompletedAtUtc",bo."CancelledAtUtc",bo."LatestReason",bo."ReportAtUtc"
ORDER BY bo."ReportAtUtc" DESC,bo."CreatedAtUtc" DESC
LIMIT 500;
$$;

CREATE OR REPLACE FUNCTION public.report_ordersummary(p_tenantid uuid,p_branchid uuid,p_datefrom timestamptz,p_dateto timestamptz,p_statuscode text,p_search text)
RETURNS TABLE("TotalOrders" integer,"CompletedOrders" integer,"CancelledOrders" integer,"TotalOrderValue" numeric,"AverageOrderValue" numeric,"AverageReadyMinutes" numeric)
LANGUAGE sql STABLE AS $$
WITH status_rollup AS (
    SELECT
        h."OrderId",
        MIN(h."CreatedAtUtc") FILTER (WHERE h."StatusCode"='Completed') AS "CompletedAtUtc",
        MAX(h."CreatedAtUtc") FILTER (WHERE h."StatusCode" IN ('Cancelled','Void')) AS "CancelledAtUtc"
    FROM "OrderStatusHistory" h
    WHERE h."TenantId"=p_tenantid
    GROUP BY h."OrderId"
),
filtered_orders AS (
    SELECT
        o."OrderId",
        o."OrderStatusCode",
        o."TotalAmount",
        CASE
            WHEN lower(COALESCE(p_statuscode,'')) IN ('cancelled','void') THEN COALESCE(sr."CancelledAtUtc",o."UpdatedAtUtc",o."CreatedAtUtc")
            WHEN lower(COALESCE(p_statuscode,''))='completed' THEN COALESCE(sr."CompletedAtUtc",o."UpdatedAtUtc",o."CreatedAtUtc")
            ELSE o."CreatedAtUtc"
        END AS "ReportAtUtc"
    FROM "Orders" o
    JOIN "BranchTables" bt ON bt."TableId"=o."TableId"
    LEFT JOIN status_rollup sr ON sr."OrderId"=o."OrderId"
    WHERE o."TenantId"=p_tenantid
      AND (p_branchid IS NULL OR o."BranchId"=p_branchid)
      AND (p_statuscode IS NULL OR lower(o."OrderStatusCode")=lower(p_statuscode))
      AND (
          p_search IS NULL
          OR o."CustomerName" ILIKE '%'||p_search||'%'
          OR o."CustomerWhatsApp" ILIKE '%'||p_search||'%'
          OR bt."Name" ILIKE '%'||p_search||'%'
          OR o."OrderId"::text ILIKE '%'||p_search||'%'
      )
)
SELECT
    COUNT(*)::integer,
    COUNT(*) FILTER (WHERE "OrderStatusCode"='Completed')::integer,
    COUNT(*) FILTER (WHERE "OrderStatusCode" IN ('Cancelled','Void'))::integer,
    COALESCE(SUM("TotalAmount"),0),
    COALESCE(AVG("TotalAmount"),0),
    0::numeric
FROM filtered_orders
WHERE (p_datefrom IS NULL OR "ReportAtUtc">=p_datefrom)
  AND (p_dateto IS NULL OR "ReportAtUtc"<p_dateto);
$$;
""";

    private const string OrderItemCancellationSql = """
ALTER TABLE "OrderItems"
ADD COLUMN IF NOT EXISTS "CancelledQuantity" integer NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "CancelledReason" varchar(300) NULL,
ADD COLUMN IF NOT EXISTS "CancelledAtUtc" timestamptz NULL,
ADD COLUMN IF NOT EXISTS "CancelledByUserId" uuid NULL REFERENCES "Users" ("UserId");

ALTER TABLE "OrderItems"
DROP CONSTRAINT IF EXISTS "CK_OrderItems_CancelledQuantity";

ALTER TABLE "OrderItems"
ADD CONSTRAINT "CK_OrderItems_CancelledQuantity" CHECK ("CancelledQuantity" >= 0 AND "CancelledQuantity" <= "Quantity");

DROP FUNCTION IF EXISTS public.publicorder_getitemsbyorder(uuid);
CREATE OR REPLACE FUNCTION public.publicorder_getitemsbyorder(p_orderid uuid)
RETURNS TABLE("OrderItemId" uuid,"OrderId" uuid,"MenuItemId" uuid,"MenuItemVariantId" uuid,"MenuItemName" varchar,"VariantName" varchar,"ItemNote" varchar,"DietTypeCode" varchar,"UnitPrice" numeric,"Quantity" integer,"LineTotal" numeric)
LANGUAGE sql STABLE AS $$
    SELECT oi."OrderItemId",oi."OrderId",oi."MenuItemId",oi."MenuItemVariantId",oi."MenuItemName",oi."VariantName",oi."ItemNote",oi."DietTypeCode",oi."UnitPrice",(oi."Quantity" - oi."CancelledQuantity")::integer,round(oi."UnitPrice" * (oi."Quantity" - oi."CancelledQuantity"),2)
    FROM "OrderItems" oi
    WHERE oi."OrderId"=p_orderid AND (oi."Quantity" - oi."CancelledQuantity") > 0
    ORDER BY oi."RowId";
$$;

DROP FUNCTION IF EXISTS public.adminorder_getitemsbybranch(uuid,uuid);
CREATE OR REPLACE FUNCTION public.adminorder_getitemsbybranch(p_tenantid uuid,p_branchid uuid)
RETURNS TABLE("OrderItemId" uuid,"OrderId" uuid,"MenuItemId" uuid,"MenuItemVariantId" uuid,"MenuItemName" varchar,"VariantName" varchar,"ItemNote" varchar,"DietTypeCode" varchar,"UnitPrice" numeric,"Quantity" integer,"LineTotal" numeric,"CancelledQuantity" integer,"ActiveQuantity" integer,"ActiveLineTotal" numeric,"CancelledReason" varchar,"CancelledAtUtc" timestamptz)
LANGUAGE sql STABLE AS $$
    SELECT oi."OrderItemId",oi."OrderId",oi."MenuItemId",oi."MenuItemVariantId",oi."MenuItemName",oi."VariantName",oi."ItemNote",oi."DietTypeCode",oi."UnitPrice",oi."Quantity",oi."LineTotal",oi."CancelledQuantity",(oi."Quantity" - oi."CancelledQuantity")::integer,round(oi."UnitPrice" * (oi."Quantity" - oi."CancelledQuantity"),2),oi."CancelledReason",oi."CancelledAtUtc"
    FROM "OrderItems" oi
    JOIN "Orders" o ON o."OrderId"=oi."OrderId"
    WHERE oi."TenantId"=p_tenantid AND oi."BranchId"=p_branchid
    ORDER BY oi."RowId";
$$;

CREATE OR REPLACE FUNCTION public.adminorder_cancelitem(p_tenantid uuid,p_branchid uuid,p_orderid uuid,p_orderitemid uuid,p_cancelquantity integer,p_reason text,p_changedbyuserid uuid)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"TableName" varchar,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz,"ClosedAtUtc" timestamptz,"LatestReason" varchar)
LANGUAGE plpgsql AS $$
DECLARE
    order_row record;
    item_row record;
    bill_row record;
    billing record;
    active_subtotal numeric := 0;
    discount numeric := 0;
    taxable numeric := 0;
    tax numeric := 0;
    service_charge numeric := 0;
    total_before_rounding numeric := 0;
    rounding_amount numeric := 0;
    payable_total numeric := 0;
BEGIN
    SELECT o.* INTO order_row FROM "Orders" o WHERE o."TenantId"=p_tenantid AND o."BranchId"=p_branchid AND o."OrderId"=p_orderid FOR UPDATE;
    IF order_row."OrderId" IS NULL THEN PERFORM public.raise_app_error(51708); END IF;
    IF order_row."OrderStatusCode" IN ('Completed','Cancelled') THEN PERFORM public.raise_app_error(51710); END IF;
    IF COALESCE(p_cancelquantity,0) <= 0 THEN PERFORM public.raise_app_error(51711); END IF;
    IF NULLIF(btrim(p_reason),'') IS NULL OR length(btrim(p_reason)) > 300 THEN PERFORM public.raise_app_error(51712); END IF;

    SELECT oi.* INTO item_row FROM "OrderItems" oi WHERE oi."TenantId"=p_tenantid AND oi."BranchId"=p_branchid AND oi."OrderId"=p_orderid AND oi."OrderItemId"=p_orderitemid FOR UPDATE;
    IF item_row."OrderItemId" IS NULL THEN PERFORM public.raise_app_error(51713); END IF;
    IF p_cancelquantity > (item_row."Quantity" - item_row."CancelledQuantity") THEN PERFORM public.raise_app_error(51711); END IF;

    SELECT ob.* INTO bill_row FROM "OrderBills" ob WHERE ob."TenantId"=p_tenantid AND ob."BranchId"=p_branchid AND ob."OrderId"=p_orderid FOR UPDATE;
    IF bill_row."OrderBillId" IS NOT NULL AND bill_row."PaymentStatusCode" <> 'Unpaid' THEN PERFORM public.raise_app_error(51714); END IF;

    UPDATE "OrderItems" SET "CancelledQuantity"="CancelledQuantity" + p_cancelquantity,"CancelledReason"=btrim(p_reason),"CancelledAtUtc"=public.app_now(),"CancelledByUserId"=p_changedbyuserid WHERE "OrderItemId"=p_orderitemid;
    SELECT COALESCE(round(SUM(oi."UnitPrice" * (oi."Quantity" - oi."CancelledQuantity")),2),0) INTO active_subtotal FROM "OrderItems" oi WHERE oi."TenantId"=p_tenantid AND oi."BranchId"=p_branchid AND oi."OrderId"=p_orderid;

    IF order_row."AppliedBranchOfferId" IS NOT NULL AND active_subtotal > 0 THEN
        SELECT round(LEAST(active_subtotal,GREATEST(0,CASE WHEN bo."MaxDiscountAmount" IS NOT NULL THEN LEAST(CASE bo."DiscountTypeCode" WHEN 'Percentage' THEN round(active_subtotal * bo."DiscountValue" / 100,2) ELSE round(bo."DiscountValue",2) END,bo."MaxDiscountAmount") ELSE CASE bo."DiscountTypeCode" WHEN 'Percentage' THEN round(active_subtotal * bo."DiscountValue" / 100,2) ELSE round(bo."DiscountValue",2) END END)),2)
        INTO discount
        FROM "BranchOffers" bo
        WHERE bo."TenantId"=p_tenantid AND bo."BranchId"=p_branchid AND bo."BranchOfferId"=order_row."AppliedBranchOfferId" AND bo."DiscountTypeCode" <> 'DisplayOnly' AND bo."DiscountValue" > 0 AND active_subtotal >= bo."MinimumOrderAmount";
    END IF;
    discount := COALESCE(discount,0);

    SELECT COALESCE(bs."TaxEnabled",false) "TaxEnabled",COALESCE(bs."TaxRate",0) "TaxRate",COALESCE(bs."TaxMode",'Exclusive') "TaxMode",COALESCE(bs."ServiceChargeEnabled",false) "ServiceChargeEnabled",COALESCE(bs."ServiceChargeRate",0) "ServiceChargeRate",COALESCE(bs."RoundingMode",'None') "RoundingMode"
    INTO billing
    FROM "Branches" b
    LEFT JOIN "BranchBillingSettings" bs ON bs."TenantId"=b."TenantId" AND bs."BranchId"=b."BranchId"
    WHERE b."TenantId"=p_tenantid AND b."BranchId"=p_branchid;

    taxable := round(GREATEST(active_subtotal - discount,0),2);
    IF billing."TaxEnabled" AND billing."TaxRate" > 0 THEN tax := CASE WHEN billing."TaxMode" = 'Inclusive' THEN round(taxable - taxable / (1 + billing."TaxRate" / 100),2) ELSE round(taxable * billing."TaxRate" / 100,2) END; END IF;
    IF billing."ServiceChargeEnabled" AND billing."ServiceChargeRate" > 0 THEN service_charge := round(taxable * billing."ServiceChargeRate" / 100,2); END IF;
    total_before_rounding := round((CASE WHEN billing."TaxMode" = 'Inclusive' THEN taxable ELSE taxable + tax END) + service_charge,2);
    rounding_amount := CASE WHEN billing."RoundingMode" IN ('NearestRupee','Nearest') THEN round(total_before_rounding) - total_before_rounding ELSE 0 END;
    payable_total := round(total_before_rounding + rounding_amount,2);

    UPDATE "Orders" SET "SubtotalAmount"=active_subtotal,"AppliedOfferDiscountAmount"=discount,"TotalAmount"=payable_total,"OrderStatusCode"=CASE WHEN active_subtotal <= 0 THEN 'Cancelled' ELSE "OrderStatusCode" END,"UpdatedAtUtc"=public.app_now() WHERE "OrderId"=p_orderid;
    IF active_subtotal <= 0 THEN
        INSERT INTO "OrderStatusHistory" ("OrderStatusHistoryId","TenantId","BranchId","OrderId","StatusCode","Reason","ChangedByUserId") VALUES (gen_random_uuid(),p_tenantid,p_branchid,p_orderid,'Cancelled',btrim(p_reason),p_changedbyuserid);
    END IF;
    IF bill_row."OrderBillId" IS NOT NULL THEN
        UPDATE "OrderBills" SET "SubtotalAmount"=active_subtotal,"DiscountAmount"=discount,"TaxableAmount"=taxable,"TaxAmount"=tax,"ServiceChargeAmount"=service_charge,"RoundingAmount"=rounding_amount,"TotalAmount"=payable_total,"UpdatedAtUtc"=public.app_now() WHERE "OrderBillId"=bill_row."OrderBillId";
    END IF;

    RETURN QUERY SELECT * FROM public.adminorder_getlistbybranch(p_tenantid,p_branchid,true) a WHERE a."OrderId"=p_orderid;
END;
$$;

DROP FUNCTION IF EXISTS public.publiccustomer_recentorderitemsbycustomer(uuid);
CREATE OR REPLACE FUNCTION public.publiccustomer_recentorderitemsbycustomer(p_customerid uuid)
RETURNS TABLE("OrderId" uuid,"MenuItemId" uuid,"MenuItemVariantId" uuid,"MenuItemName" varchar,"VariantName" varchar,"ItemNote" varchar,"DietTypeCode" varchar,"Quantity" integer)
LANGUAGE sql STABLE AS $$
    SELECT oi."OrderId",oi."MenuItemId",oi."MenuItemVariantId",oi."MenuItemName",oi."VariantName",oi."ItemNote",oi."DietTypeCode",(oi."Quantity" - oi."CancelledQuantity")::integer
    FROM "OrderItems" oi
    JOIN (SELECT o."OrderId" FROM "Orders" o WHERE o."CustomerId"=p_customerid ORDER BY o."CreatedAtUtc" DESC LIMIT 5) recent ON recent."OrderId"=oi."OrderId"
    WHERE (oi."Quantity" - oi."CancelledQuantity") > 0
    ORDER BY oi."RowId";
$$;

DROP FUNCTION IF EXISTS public.report_items(uuid,uuid,timestamptz,timestamptz,text,text);
CREATE OR REPLACE FUNCTION public.report_items(p_tenantid uuid,p_branchid uuid,p_datefrom timestamptz,p_dateto timestamptz,p_statuscode text,p_search text)
RETURNS TABLE("ItemName" varchar,"VariantName" varchar,"Quantity" integer,"OrderCount" integer,"TotalValue" numeric)
LANGUAGE sql STABLE AS $$
    SELECT oi."MenuItemName",oi."VariantName",SUM(oi."Quantity" - oi."CancelledQuantity")::integer,COUNT(DISTINCT oi."OrderId")::integer,SUM(round(oi."UnitPrice" * (oi."Quantity" - oi."CancelledQuantity"),2))
    FROM "OrderItems" oi
    JOIN "Orders" o ON o."OrderId"=oi."OrderId"
    WHERE o."TenantId"=p_tenantid AND (p_branchid IS NULL OR o."BranchId"=p_branchid) AND (oi."Quantity" - oi."CancelledQuantity") > 0
    GROUP BY oi."MenuItemName",oi."VariantName"
    ORDER BY SUM(round(oi."UnitPrice" * (oi."Quantity" - oi."CancelledQuantity"),2)) DESC;
$$;
""";
}
