using Npgsql;

namespace QRApp.Api.Database;

public static class DatabaseStartupPatches
{
    public static async Task ApplyDatabaseStartupPatchesAsync(this WebApplication app)
    {
        var connectionString = app.Configuration.GetConnectionString("Postgres");
        if (string.IsNullOrWhiteSpace(connectionString))
        {
            return;
        }

        var builder = new NpgsqlConnectionStringBuilder(connectionString);
        if (string.IsNullOrWhiteSpace(builder.Timezone))
        {
            builder.Timezone = "Asia/Kolkata";
        }

        var logger = app.Services.GetRequiredService<ILoggerFactory>().CreateLogger("DatabaseStartupPatches");
        await using var connection = new NpgsqlConnection(builder.ConnectionString);
        await connection.OpenAsync();

        await using var command = new NpgsqlCommand(PublicOrderSql, connection);
        await command.ExecuteNonQueryAsync();

        logger.LogInformation("Applied database startup patches.");
    }

    private const string PublicOrderSql = """
ALTER TABLE "MenuItems"
ADD COLUMN IF NOT EXISTS "DietTypeCode" varchar(32) NOT NULL DEFAULT 'Unspecified';

ALTER TABLE "OrderItems"
ADD COLUMN IF NOT EXISTS "DietTypeCode" varchar(32) NOT NULL DEFAULT 'Unspecified';

CREATE TABLE IF NOT EXISTS "QrVisitSessions" (
    "QrSessionId" uuid PRIMARY KEY,
    "TenantId" uuid NOT NULL REFERENCES "Tenants"("TenantId") ON DELETE CASCADE,
    "BranchId" uuid NOT NULL REFERENCES "Branches"("BranchId") ON DELETE CASCADE,
    "TableId" uuid NOT NULL REFERENCES "BranchTables"("TableId") ON DELETE CASCADE,
    "QrToken" varchar(80) NOT NULL,
    "StartedAtUtc" timestamptz NOT NULL DEFAULT public.app_now(),
    "ExpiresAtUtc" timestamptz NOT NULL,
    "RevokedAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now()
);

CREATE INDEX IF NOT EXISTS "IX_QrVisitSessions_QrToken_ExpiresAtUtc" ON "QrVisitSessions" ("QrToken","ExpiresAtUtc");

CREATE TABLE IF NOT EXISTS "SuperAdminUsers" (
    "SuperAdminUserId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "Email" varchar(256) NOT NULL,
    "DisplayName" varchar(160) NOT NULL,
    "PasswordHash" varchar(512) NOT NULL,
    "RoleCode" varchar(40) NOT NULL DEFAULT 'super_admin',
    "IsActive" boolean NOT NULL DEFAULT true,
    "LastLoginAtUtc" timestamptz NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now(),
    "UpdatedAtUtc" timestamptz NULL,
    "RowVersion" bytea NOT NULL DEFAULT gen_random_bytes(8),
    CONSTRAINT "UQ_SuperAdminUsers_Email" UNIQUE ("Email"),
    CONSTRAINT "CK_SuperAdminUsers_RoleCode" CHECK ("RoleCode" IN ('super_admin', 'support_admin', 'sales_admin'))
);

CREATE TABLE IF NOT EXISTS "SuperAdminAuditEntries" (
    "SuperAdminAuditEntryId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NULL REFERENCES "Tenants" ("TenantId"),
    "SuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "ActionCode" varchar(80) NOT NULL,
    "Summary" varchar(500) NOT NULL,
    "MetadataJson" text NULL,
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now()
);

CREATE TABLE IF NOT EXISTS "SuperAdminInternalNotes" (
    "SuperAdminInternalNoteId" uuid PRIMARY KEY,
    "RowId" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "TenantId" uuid NOT NULL REFERENCES "Tenants" ("TenantId") ON DELETE CASCADE,
    "Note" varchar(1000) NOT NULL,
    "CreatedBySuperAdminUserId" uuid NOT NULL REFERENCES "SuperAdminUsers" ("SuperAdminUserId"),
    "CreatedAtUtc" timestamptz NOT NULL DEFAULT public.app_now()
);

CREATE INDEX IF NOT EXISTS "IX_SuperAdminAuditEntries_TenantId_CreatedAtUtc" ON "SuperAdminAuditEntries" ("TenantId", "CreatedAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_SuperAdminAuditEntries_CreatedAtUtc" ON "SuperAdminAuditEntries" ("CreatedAtUtc" DESC);
CREATE INDEX IF NOT EXISTS "IX_SuperAdminInternalNotes_TenantId_CreatedAtUtc" ON "SuperAdminInternalNotes" ("TenantId", "CreatedAtUtc" DESC);

DROP FUNCTION IF EXISTS public.publicorder_getitemsbyorder(uuid);

CREATE OR REPLACE FUNCTION public.tenant_public_access_allowed(p_tenantid uuid)
RETURNS boolean
LANGUAGE sql STABLE AS $$
    SELECT COALESCE((
        SELECT t."IsActive"
           AND t."AccountStatusCode" = 'Active'
           AND (
                t."SubscriptionStatusCode" IN ('Active','ManualActive')
                OR (
                    t."SubscriptionStatusCode" = 'Trialing'
                    AND (t."TrialStartAtUtc" IS NULL OR t."TrialStartAtUtc" <= public.app_now())
                    AND t."TrialEndAtUtc" IS NOT NULL
                    AND t."TrialEndAtUtc" >= public.app_now()
                )
           )
        FROM "Tenants" t
        WHERE t."TenantId" = p_tenantid
    ), false);
$$;

CREATE OR REPLACE FUNCTION public.publicqr_assert_tenant_available(p_qrtoken text)
RETURNS void
LANGUAGE plpgsql AS $$
DECLARE
    tenant_id uuid;
BEGIN
    SELECT bt."TenantId"
    INTO tenant_id
    FROM "BranchTables" bt
    WHERE bt."QrToken" = p_qrtoken AND bt."IsActive"
    LIMIT 1;

    IF tenant_id IS NOT NULL AND NOT public.tenant_public_access_allowed(tenant_id) THEN
        PERFORM public.raise_app_error(52002);
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.qrvisitsession_create(p_qrtoken text,p_qrsessionid uuid,p_ttlminutes integer)
RETURNS TABLE("QrSessionId" uuid,"BranchId" uuid,"TableId" uuid,"StartedAtUtc" timestamptz,"ExpiresAtUtc" timestamptz,"IsExpired" boolean)
LANGUAGE plpgsql AS $$
DECLARE
    ctx record;
    started_at timestamptz := public.app_now();
    ttl_minutes integer := LEAST(GREATEST(COALESCE(p_ttlminutes,240),15),720);
BEGIN
    PERFORM public.publicqr_assert_tenant_available(p_qrtoken);

    SELECT bt."TenantId",bt."BranchId",bt."TableId"
    INTO ctx
    FROM "BranchTables" bt
    JOIN "Branches" b ON b."BranchId"=bt."BranchId" AND b."IsActive"
    WHERE bt."QrToken"=p_qrtoken AND bt."IsActive";

    IF ctx."TableId" IS NULL THEN
        PERFORM public.raise_app_error(51701);
    END IF;

    INSERT INTO "QrVisitSessions" ("QrSessionId","TenantId","BranchId","TableId","QrToken","StartedAtUtc","ExpiresAtUtc")
    VALUES (p_qrsessionid,ctx."TenantId",ctx."BranchId",ctx."TableId",p_qrtoken,started_at,started_at + make_interval(mins => ttl_minutes));

    RETURN QUERY
    SELECT qvs."QrSessionId",qvs."BranchId",qvs."TableId",qvs."StartedAtUtc",qvs."ExpiresAtUtc",(qvs."ExpiresAtUtc" <= public.app_now() OR qvs."RevokedAtUtc" IS NOT NULL)
    FROM "QrVisitSessions" qvs
    WHERE qvs."QrSessionId"=p_qrsessionid;
END;
$$;

CREATE OR REPLACE FUNCTION public.qrvisitsession_assert_active(p_qrtoken text,p_qrsessionid uuid)
RETURNS TABLE("TenantId" uuid,"BranchId" uuid,"TableId" uuid)
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM public.publicqr_assert_tenant_available(p_qrtoken);

    RETURN QUERY
    SELECT qvs."TenantId",qvs."BranchId",qvs."TableId"
    FROM "QrVisitSessions" qvs
    JOIN "BranchTables" bt ON bt."TableId"=qvs."TableId" AND bt."QrToken"=p_qrtoken AND bt."IsActive"
    JOIN "Branches" b ON b."BranchId"=qvs."BranchId" AND b."IsActive"
    WHERE qvs."QrSessionId"=p_qrsessionid
      AND qvs."QrToken"=p_qrtoken
      AND qvs."RevokedAtUtc" IS NULL
      AND qvs."ExpiresAtUtc" > public.app_now();

    IF NOT FOUND THEN
        PERFORM public.raise_app_error(52001);
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_select(p_orderid uuid)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE sql STABLE AS $$ SELECT o."OrderId",o."TenantId",o."BranchId",o."TableId",o."OrderStatusCode",o."CustomerName",o."CustomerWhatsApp",o."Notes",o."SubtotalAmount",o."TotalAmount",o."AppliedBranchOfferId",o."AppliedOfferTitle",o."AppliedOfferDiscountAmount",o."CreatedAtUtc",o."UpdatedAtUtc" FROM "Orders" o WHERE o."OrderId"=p_orderid; $$;

CREATE OR REPLACE FUNCTION public.publicorder_getitemsbyorder(p_orderid uuid)
RETURNS TABLE("OrderItemId" uuid,"OrderId" uuid,"MenuItemId" uuid,"MenuItemVariantId" uuid,"MenuItemName" varchar,"VariantName" varchar,"ItemNote" varchar,"DietTypeCode" varchar,"UnitPrice" numeric,"Quantity" integer,"LineTotal" numeric)
LANGUAGE sql STABLE AS $$ SELECT oi."OrderItemId",oi."OrderId",oi."MenuItemId",oi."MenuItemVariantId",oi."MenuItemName",oi."VariantName",oi."ItemNote",oi."DietTypeCode",oi."UnitPrice",oi."Quantity",oi."LineTotal" FROM "OrderItems" oi WHERE oi."OrderId"=p_orderid ORDER BY oi."RowId"; $$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(p_qrtoken text,p_orderid uuid,p_customername text,p_customerwhatsapp text,p_notes text,p_itemsjson text,p_marketingconsent boolean,p_marketingconsentsource text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
DECLARE
    ctx record;
    customer_id uuid;
    subtotal numeric;
    billing record;
    offer_id uuid;
    offer_title varchar;
    discount numeric := 0;
    taxable numeric := 0;
    tax numeric := 0;
    service_charge numeric := 0;
    total_before_rounding numeric := 0;
    rounding_amount numeric := 0;
    payable_total numeric := 0;
BEGIN
    SELECT bt."TenantId",bt."BranchId",bt."TableId",COALESCE(bos."EnableDirectQrOrdering",false) enabled,COALESCE(bos."RequireCustomerName",false) req_name,COALESCE(bos."RequireCustomerWhatsApp",false) req_whatsapp
    INTO ctx FROM "BranchTables" bt JOIN "Branches" b ON b."BranchId"=bt."BranchId" AND b."IsActive" LEFT JOIN "BranchOrderSettings" bos ON bos."BranchId"=bt."BranchId" WHERE bt."QrToken"=p_qrtoken AND bt."IsActive";
    IF ctx."TableId" IS NULL THEN PERFORM public.raise_app_error(51701); END IF;
    IF NOT ctx.enabled THEN PERFORM public.raise_app_error(51702); END IF;
    IF ctx.req_name AND NULLIF(btrim(p_customername),'') IS NULL THEN PERFORM public.raise_app_error(51703); END IF;
    IF ctx.req_whatsapp AND NULLIF(btrim(p_customerwhatsapp),'') IS NULL THEN PERFORM public.raise_app_error(51704); END IF;

    CREATE TEMP TABLE tmp_order_items ON COMMIT DROP AS
    SELECT gen_random_uuid() "OrderItemId", mi."MenuItemId", v."MenuItemVariantId", mi."Name" "MenuItemName", v."Name" "VariantName", NULLIF(x->>'itemNote','') "ItemNote", mi."DietTypeCode", COALESCE(v."Price",mi."Price") "UnitPrice", GREATEST(COALESCE((x->>'quantity')::integer,0),0) "Quantity"
    FROM jsonb_array_elements(COALESCE(NULLIF(p_itemsjson,'')::jsonb,'[]'::jsonb)) x
    JOIN "MenuItems" mi ON mi."MenuItemId"=(x->>'menuItemId')::uuid AND mi."TenantId"=ctx."TenantId" AND mi."BranchId"=ctx."BranchId" AND mi."IsActive" AND mi."IsAvailable"
    LEFT JOIN "MenuItemVariants" v ON v."MenuItemVariantId"=NULLIF(x->>'menuItemVariantId','')::uuid AND v."MenuItemId"=mi."MenuItemId" AND v."IsAvailable";
    DELETE FROM tmp_order_items WHERE "Quantity" <= 0;
    IF NOT EXISTS (SELECT 1 FROM tmp_order_items) THEN PERFORM public.raise_app_error(51705); END IF;
    SELECT SUM("UnitPrice"*"Quantity") INTO subtotal FROM tmp_order_items;

    IF NULLIF(btrim(p_customerwhatsapp),'') IS NOT NULL THEN
        INSERT INTO "Customers" ("CustomerId","TenantId","BranchId","Name","WhatsAppNumber","VisitCount","LastVisitAtUtc","MarketingConsent","MarketingConsentSource","MarketingConsentAtUtc")
        VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",COALESCE(NULLIF(p_customername,''),'Guest'),p_customerwhatsapp,1,public.app_now(),p_marketingconsent,p_marketingconsentsource,CASE WHEN p_marketingconsent THEN public.app_now() END)
        ON CONFLICT ON CONSTRAINT "UQ_Customers_TenantId_BranchId_WhatsAppNumber" DO UPDATE SET "Name"=COALESCE(NULLIF(EXCLUDED."Name",''),"Customers"."Name"),"VisitCount"="Customers"."VisitCount"+1,"LastVisitAtUtc"=public.app_now(),"MarketingConsent"=("Customers"."MarketingConsent" OR EXCLUDED."MarketingConsent"),"UpdatedAtUtc"=public.app_now()
        RETURNING "CustomerId" INTO customer_id;
    END IF;

    SELECT
        COALESCE(bs."TaxEnabled",false) "TaxEnabled",
        COALESCE(bs."TaxRate",0) "TaxRate",
        COALESCE(bs."TaxMode",'Exclusive') "TaxMode",
        COALESCE(bs."ServiceChargeEnabled",false) "ServiceChargeEnabled",
        COALESCE(bs."ServiceChargeRate",0) "ServiceChargeRate",
        COALESCE(bs."RoundingMode",'None') "RoundingMode"
    INTO billing
    FROM "Branches" b
    LEFT JOIN "BranchBillingSettings" bs ON bs."TenantId"=b."TenantId" AND bs."BranchId"=b."BranchId"
    WHERE b."TenantId"=ctx."TenantId" AND b."BranchId"=ctx."BranchId";

    SELECT selected_offer."BranchOfferId", selected_offer."Title", selected_offer.computed_discount
    INTO offer_id, offer_title, discount
    FROM (
        SELECT bo.*,
               round(LEAST(
                   subtotal,
                   GREATEST(
                       0,
                       CASE
                           WHEN bo."MaxDiscountAmount" IS NOT NULL THEN LEAST(
                               CASE bo."DiscountTypeCode"
                                   WHEN 'Percentage' THEN round(subtotal * bo."DiscountValue" / 100,2)
                                   ELSE round(bo."DiscountValue",2)
                               END,
                               bo."MaxDiscountAmount"
                           )
                           ELSE CASE bo."DiscountTypeCode"
                               WHEN 'Percentage' THEN round(subtotal * bo."DiscountValue" / 100,2)
                               ELSE round(bo."DiscountValue",2)
                           END
                       END
                   )
               ),2) AS computed_discount
        FROM "BranchOffers" bo
        WHERE bo."TenantId"=ctx."TenantId"
          AND bo."BranchId"=ctx."BranchId"
          AND bo."IsActive"
          AND bo."AutoApply"
          AND bo."DiscountTypeCode" <> 'DisplayOnly'
          AND bo."DiscountValue" > 0
          AND subtotal >= bo."MinimumOrderAmount"
          AND (bo."StartsAtUtc" IS NULL OR bo."StartsAtUtc" <= public.app_now())
          AND (bo."EndsAtUtc" IS NULL OR bo."EndsAtUtc" >= public.app_now())
        ORDER BY computed_discount DESC, bo."DisplayOrder", bo."Title"
        LIMIT 1
    ) selected_offer;
    discount := COALESCE(discount,0);

    taxable := round(GREATEST(subtotal - discount,0),2);
    IF billing."TaxEnabled" AND billing."TaxRate" > 0 THEN
        tax := CASE
            WHEN billing."TaxMode" = 'Inclusive' THEN round(taxable - taxable / (1 + billing."TaxRate" / 100),2)
            ELSE round(taxable * billing."TaxRate" / 100,2)
        END;
    END IF;
    IF billing."ServiceChargeEnabled" AND billing."ServiceChargeRate" > 0 THEN
        service_charge := round(taxable * billing."ServiceChargeRate" / 100,2);
    END IF;
    total_before_rounding := round((CASE WHEN billing."TaxMode" = 'Inclusive' THEN taxable ELSE taxable + tax END) + service_charge,2);
    rounding_amount := CASE WHEN billing."RoundingMode" IN ('NearestRupee','Nearest') THEN round(total_before_rounding) - total_before_rounding ELSE 0 END;
    payable_total := round(total_before_rounding + rounding_amount,2);

    INSERT INTO "Orders" ("OrderId","TenantId","BranchId","TableId","CustomerId","CustomerName","CustomerWhatsApp","Notes","SubtotalAmount","AppliedBranchOfferId","AppliedOfferTitle","AppliedOfferDiscountAmount","TotalAmount")
    VALUES (p_orderid,ctx."TenantId",ctx."BranchId",ctx."TableId",customer_id,p_customername,p_customerwhatsapp,p_notes,subtotal,offer_id,offer_title,discount,payable_total);
    INSERT INTO "OrderItems" ("OrderItemId","TenantId","BranchId","OrderId","MenuItemId","MenuItemVariantId","MenuItemName","VariantName","ItemNote","DietTypeCode","UnitPrice","Quantity","LineTotal")
    SELECT "OrderItemId",ctx."TenantId",ctx."BranchId",p_orderid,"MenuItemId","MenuItemVariantId","MenuItemName","VariantName","ItemNote","DietTypeCode","UnitPrice","Quantity","UnitPrice"*"Quantity" FROM tmp_order_items;
    INSERT INTO "OrderStatusHistory" ("OrderStatusHistoryId","TenantId","BranchId","OrderId","StatusCode") VALUES (gen_random_uuid(),ctx."TenantId",ctx."BranchId",p_orderid,'Placed');
    RETURN QUERY SELECT * FROM public.publicorder_select(p_orderid);
END;
$$;

CREATE OR REPLACE FUNCTION public.publicorder_createfromqrtoken(p_qrtoken text,p_qrsessionid uuid,p_orderid uuid,p_customername text,p_customerwhatsapp text,p_notes text,p_itemsjson text,p_marketingconsent boolean,p_marketingconsentsource text)
RETURNS TABLE("OrderId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"OrderStatusCode" varchar,"CustomerName" varchar,"CustomerWhatsApp" varchar,"Notes" varchar,"SubtotalAmount" numeric,"TotalAmount" numeric,"AppliedBranchOfferId" uuid,"AppliedOfferTitle" varchar,"AppliedOfferDiscountAmount" numeric,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM public.qrvisitsession_assert_active(p_qrtoken,p_qrsessionid);
    RETURN QUERY SELECT * FROM public.publicorder_createfromqrtoken(p_qrtoken,p_orderid,p_customername,p_customerwhatsapp,p_notes,p_itemsjson,p_marketingconsent,p_marketingconsentsource);
END;
$$;

CREATE OR REPLACE FUNCTION public.waitercall_createfromqrtoken(p_qrtoken text,p_qrsessionid uuid,p_waitercallid uuid,p_customername text,p_note text)
RETURNS TABLE("WaiterCallId" uuid,"TenantId" uuid,"BranchId" uuid,"TableId" uuid,"TableName" varchar,"StatusCode" varchar,"CustomerName" varchar,"Note" varchar,"CreatedAtUtc" timestamptz,"UpdatedAtUtc" timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
    PERFORM 1 FROM public.qrvisitsession_assert_active(p_qrtoken,p_qrsessionid);
    RETURN QUERY SELECT * FROM public.waitercall_createfromqrtoken(p_qrtoken,p_waitercallid,p_customername,p_note);
END;
$$;

CREATE OR REPLACE FUNCTION public.publiccustomer_lookupbyqrtoken(p_qrtoken text,p_customerwhatsapp text)
RETURNS TABLE("CustomerId" uuid,"Name" varchar,"WhatsAppNumber" varchar,"MarketingConsent" boolean,"VisitCount" integer,"TotalOrderCount" integer,"TotalOrderValue" numeric,"LastVisitAtUtc" timestamptz)
LANGUAGE sql STABLE AS $$
    SELECT c."CustomerId",c."Name",c."WhatsAppNumber",c."MarketingConsent",c."VisitCount",COUNT(o."OrderId")::integer,COALESCE(SUM(o."TotalAmount"),0),COALESCE(c."LastVisitAtUtc",c."CreatedAtUtc")
    FROM "Customers" c
    JOIN "BranchTables" bt ON bt."BranchId"=c."BranchId"
    LEFT JOIN "Orders" o ON o."CustomerId"=c."CustomerId"
    WHERE bt."QrToken"=p_qrtoken
      AND public.tenant_public_access_allowed(bt."TenantId")
      AND c."WhatsAppNumber"=p_customerwhatsapp
    GROUP BY c."CustomerId";
$$;
""";
}
